import React from 'react';

type DropdownOption = {value: string, label: string | JSX.Element}

export const directorOptions: DropdownOption[] = [
    {value: "J.J. Abrams", label: "Abrams, J.J."},
    {value: "Ben Affleck", label: "Affleck, Ben"},
    {value: "Alexandre Aja", label: "Aja, Alexandre"},
    {value: "Woody Allen", label: "Allen, Woody"},
    {value: "Fede Alvarez", label: "Alvarez, Fede"},
    {value: "Sean Anders", label: "Anders, Sean"},
    {value: "Paul Thomas Anderson", label: "Anderson, Paul Thomas"},
    {value: "Paul W.S. Anderson", label: "Anderson, Paul W.S."},
    {value: "Wes Anderson", label: "Anderson, Wes"},
    {value: "Nimród Antal", label: "Antal, Nimród"},
    {value: "Judd Apatow", label: "Apatow, Judd"},
    {value: "Michael Apted", label: "Apted, Michael"},
    {value: "Darren Aronofsky", label: "Aronofsky, Darren"},
    {value: "Miguel Arteta", label: "Arteta, Miguel"},
    {value: "Kelly Asbury", label: "Asbury, Kelly"},
    {value: "John G. Avildsen", label: "Avildsen, John G."},
    {value: "David Ayer", label: "Ayer, David"},
    {value: "Jeff Baena", label: "Baena, Jeff"},
    {value: "Wes Ball", label: "Ball, Wes"},
    {value: "Elizabeth Banks", label: "Banks, Elizabeth"},
    {value: "Daniel Barnz", label: "Barnz, Daniel"},
    {value: "Noah Baumbach", label: "Baumbach, Noah"},
    {value: "Michael Bay", label: "Bay, Michael"},
    {value: "Walt Becker", label: "Becker, Walt"},
    {value: "Timur Bekmambetov", label: "Bekmambetov, Timur"},
    {value: "William Brent Bell", label: "Bell, William Brent"},
    {value: "Peter Berg", label: "Berg, Peter"},
    {value: "Luc Besson", label: "Besson, Luc"},
    {value: "Kathryn Bigelow", label: "Bigelow, Kathryn"},
    {value: "Brad Bird", label: "Bird, Brad"},
    {value: "Shane Black", label: "Black, Shane"},
    {value: "James Bobin", label: "Bobin, James"},
    {value: "Anna Boden", label: "Boden, Anna"},
    {value: "David Bowers", label: "Bowers, David"},
    {value: "Danny Boyle", label: "Boyle, Danny"},
    {value: "Tom Brady", label: "Brady, Tom"},
    {value: "Zach Braff", label: "Braff, Zach"},
    {value: "Kenneth Branagh", label: "Branagh, Kenneth"},
    {value: "Martin Brest", label: "Brest, Martin"},
    {value: "Steven Brill", label: "Brill, Steven"},
    {value: "James L. Brooks", label: "Brooks, James L."},
    {value: "Mel Brooks", label: "Brooks, Mel"},
    {value: "Neil Burger", label: "Burger, Neil"},
    {value: "Tim Burton", label: "Burton, Tim"},
    {value: "James Cameron", label: "Cameron, James"},
    {value: "Martin Campbell", label: "Campbell, Martin"},
    {value: "Joe Carnahan", label: "Carnahan, Joe"},
    {value: "John Carpenter", label: "Carpenter, John"},
    {value: "Steve Carr", label: "Carr, Steve"},
    {value: "Thomas Carter", label: "Carter, Thomas"},
    {value: "D.J. Caruso", label: "Caruso, D.J."},
    {value: "Nick Cassavetes", label: "Cassavetes, Nick"},
    {value: "J.C. Chandor", label: "Chandor, J.C."},
    {value: "Jay Chandrasekhar", label: "Chandrasekhar, Jay"},
    {value: "Larry Charles", label: "Charles, Larry"},
    {value: "Damien Chazelle", label: "Chazelle, Damien"},
    {value: "Jon M. Chu", label: "Chu, Jon M."},
    {value: "Derek Cianfrance", label: "Cianfrance, Derek"},
    {value: "Bob Clark", label: "Clark, Bob"},
    {value: "Ron Clements & John Musker", label: "Clements, Ron & Musker, John"},
    {value: "George Clooney", label: "Clooney, George"},
    {value: "Coen Brothers ", label: "Coen Brothers"},
    {value: "Rob Cohen", label: "Cohen, Rob"},
    {value: "Jaume Collet-Serra", label: "Collet-Serra, Jaume"},
    {value: "Chris Columbus", label: "Columbus, Chris"},
    {value: "Bill Condon", label: "Condon, Bill"},
    {value: "Ryan Coogler", label: "Coogler, Ryan"},
    {value: "Scott Cooper", label: "Cooper, Scott"},
    {value: "Francis Ford Coppola", label: "Coppola, Francis Ford"},
    {value: "Sofia Coppola", label: "Coppola, Sofia"},
    {value: "Frank Coraci", label: "Coraci, Frank"},
    {value: "Wes Craven", label: "Craven, Wes"},
    {value: "Destin Daniel Cretton", label: "Cretton, Destin Daniel"},
    {value: "David Cronenberg", label: "Cronenberg, David"},
    {value: "Cameron Crowe", label: "Crowe, Cameron"},
    {value: "John Crowley", label: "Crowley, John"},
    {value: "Alfonso Cuarón", label: "Cuarón, Alfonso"},
    {value: "Richard Curtis", label: "Curtis, Richard"},
    {value: "Simon Curtis", label: "Curtis, Simon"},
    {value: "Lee Daniels", label: "Daniels, Lee"},
    {value: "Joe Dante", label: "Dante, Joe"},
    {value: "Frank Darabont", label: "Darabont, Frank"},
    {value: "Eric Darnell", label: "Darnell, Eric"},
    {value: "Andrew Davis", label: "Davis, Andrew"},
    {value: "Brian De Palma", label: "De Palma, Brian"},
    {value: "Dean DeBlois", label: "DeBlois, Dean"},
    {value: "Guillermo del Toro", label: "del Toro, Guillermo"},
    {value: "James DeMonaco", label: "DeMonaco, James"},
    {value: "Jonathan Demme", label: "Demme, Jonathan"},
    {value: "Scott Derrickson", label: "Derrickson, Scott"},
    {value: "Howard Deutch", label: "Deutch, Howard"},
    {value: "Walt Disney", label: "Disney, Walt"},
    {value: "David Dobkin", label: "Dobkin, David"},
    {value: "Pete Docter", label: "Docter, Pete"},
    {value: "Roger Donaldson", label: "Donaldson, Roger"},
    {value: "Richard Donner", label: "Donner, Richard"},
    {value: "John Erick Dowdle", label: "Dowdle, John Erick"},
    {value: "Michael Dowse", label: "Dowse, Michael"},
    {value: "Dennis Dugan", label: "Dugan, Dennis"},
    {value: "Clint Eastwood", label: "Eastwood, Clint"},
    {value: "David R. Ellis", label: "Ellis, David R."},
    {value: "Roland Emmerich", label: "Emmerich, Roland"},
    {value: "Nora Ephron", label: "Ephron, Nora"},
    {value: "Daniel Espinosa", label: "Espinosa, Daniel"},
    {value: "David Mickey Evans", label: "Evans, David Mickey"},
    {value: "Ben Falcone", label: "Falcone, Ben"},
    {value: "Bobby Farrelly & Peter Farrelly", label: "Farrelly, Bobby & Farrelly, Peter"},
    {value: "Jon Favreau", label: "Favreau, Jon"},
    {value: "Paul Feig", label: "Feig, Paul"},
    {value: "Shana Feste", label: "Feste, Shana"},
    {value: "Andy Fickman", label: "Fickman, Andy"},
    {value: "David Fincher", label: "Fincher, David"},
    {value: "Ruben Fleischer", label: "Fleischer, Ruben"},
    {value: "Andrew Fleming", label: "Fleming, Andrew"},
    {value: "Anne Fletcher", label: "Fletcher, Anne"},
    {value: "James Foley", label: "Foley, James"},
    {value: "Marc Forster", label: "Forster, Marc"},
    {value: "David Frankel", label: "Frankel, David"},
    {value: "Stephen Frears", label: "Frears, Stephen"},
    {value: "Thor Freudenthal", label: "Freudenthal, Thor"},
    {value: "Jason Friedberg & Aaron Seltzer", label: "Friedberg, Jason & Seltzer, Aaron"},
    {value: "William Friedkin", label: "Friedkin, William"},
    {value: "Antoine Fuqua", label: "Fuqua, Antoine"},
    {value: "Brad Furman", label: "Furman, Brad"},
    {value: "Clyde Geronimi", label: "Geronimi, Clyde"},
    {value: "Mel Gibson", label: "Gibson, Mel"},
    {value: "Lewis Gilbert", label: "Gilbert, Lewis"},
    {value: "Craig Gillespie", label: "Gillespie, Craig"},
    {value: "Terry Gilliam", label: "Gilliam, Terry"},
    {value: "Tony Gilroy", label: "Gilroy, Tony"},
    {value: "John Glen", label: "Glen, John"},
    {value: "Will Gluck", label: "Gluck, Will"},
    {value: "Josh Gordon", label: "Gordon, Josh"},
    {value: "Seth Gordon", label: "Gordon, Seth"},
    {value: "Raja Gosnell", label: "Gosnell, Raja"},
    {value: "F. Gary Gray", label: "Gray, F. Gary"},
    {value: "James Gray", label: "Gray, James"},
    {value: "David Gordon Green", label: "Green, David Gordon"},
    {value: "Luke Greenfield", label: "Greenfield, Luke"},
    {value: "Paul Greengrass", label: "Greengrass, Paul"},
    {value: "Kevin Greutert", label: "Greutert, Kevin"},
    {value: "Luca Guadagnino", label: "Guadagnino, Luca"},
    {value: "Christopher Guest", label: "Guest, Christopher"},
    {value: "James Gunn", label: "Gunn, James"},
    {value: "Taylor Hackford", label: "Hackford, Taylor"},
    {value: "Lasse Hallström", label: "Hallström, Lasse"},
    {value: "Guy Hamilton", label: "Hamilton, Guy"},
    {value: "Sanaa Hamri", label: "Hamri, Sanaa"},
    {value: "John Lee Hancock", label: "Hancock, John Lee"},
    {value: "Catherine Hardwicke", label: "Hardwicke, Catherine"},
    {value: "Renny Harlin", label: "Harlin, Renny"},
    {value: "Jimmy Hayward", label: "Hayward, Jimmy"},
    {value: "Amy Heckerling", label: "Heckerling, Amy"},
    {value: "Peter Hedges", label: "Hedges, Peter"},
    {value: "Marielle Heller", label: "Heller, Marielle"},
    {value: "Brian Henson", label: "Henson, Brian"},
    {value: "Stephen Herek", label: "Herek, Stephen"},
    {value: "Jared Hess", label: "Hess, Jared"},
    {value: "Tim Hill", label: "Hill, Tim"},
    {value: "Oliver Hirschbiegel", label: "Hirschbiegel, Oliver"},
    {value: "Bong Joon Ho", label: "Ho, Bong Joon"},
    {value: "Gavin Hood", label: "Hood, Gavin"},
    {value: "Tom Hooper", label: "Hooper, Tom"},
    {value: "Stephen Hopkins", label: "Hopkins, Stephen"},
    {value: "Ron Howard", label: "Howard, Ron"},
    {value: "John Hughes", label: "Hughes, John"},
    {value: "Mikael Håfström", label: "Håfström, Mikael"},
    {value: "Peter Jackson", label: "Jackson, Peter"},
    {value: "Mark Steven Johnson", label: "Johnson, Mark Steven"},
    {value: "Rian Johnson", label: "Johnson, Rian"},
    {value: "Joe Johnston", label: "Johnston, Joe"},
    {value: "Duncan Jones", label: "Jones, Duncan"},
    {value: "Kirk Jones", label: "Jones, Kirk"},
    {value: "Terry Jones", label: "Jones, Terry"},
    {value: "Spike Jonze", label: "Jonze, Spike"},
    {value: "Neil Jordan", label: "Jordan, Neil"},
    {value: "Jake Kasdan", label: "Kasdan, Jake"},
    {value: "Gil Kenan", label: "Kenan, Gil"},
    {value: "David Koepp", label: "Koepp, David"},
    {value: "Baltasar Kormákur", label: "Kormákur, Baltasar"},
    {value: "Joseph Kosinski", label: "Kosinski, Joseph"},
    {value: "Stanley Kubrick", label: "Kubrick, Stanley"},
    {value: "Roger Kumble", label: "Kumble, Roger"},
    {value: "Ken Kwapis", label: "Kwapis, Ken"},
    {value: "Richard LaGravenese", label: "LaGravenese, Richard"},
    {value: "John Landis", label: "Landis, John"},
    {value: "Christopher Landon", label: "Landon, Christopher"},
    {value: "Yorgos Lanthimos", label: "Lanthimos, Yorgos"},
    {value: "John Lasseter", label: "Lasseter, John"},
    {value: "Francis Lawrence", label: "Lawrence, Francis"},
    {value: "Marc Lawrence", label: "Lawrence, Marc"},
    {value: "Ang Lee", label: "Lee, Ang"},
    {value: "Malcolm D. Lee", label: "Lee, Malcolm D."},
    {value: "Spike Lee", label: "Lee, Spike"},
    {value: "David Leitch", label: "Leitch, David"},
    {value: "Michael Lembeck", label: "Lembeck, Michael"},
    {value: "Kasi Lemmons", label: "Lemmons, Kasi"},
    {value: "Sergio Leone", label: "Leone, Sergio"},
    {value: "Louis Leterrier", label: "Leterrier, Louis"},
    {value: "Rob Letterman", label: "Letterman, Rob"},
    {value: "Brian Levant", label: "Levant, Brian"},
    {value: "Jonathan Levine", label: "Levine, Jonathan"},
    {value: "Barry Levinson", label: "Levinson, Barry"},
    {value: "Shawn Levy", label: "Levy, Shawn"},
    {value: "Jonathan Liebesman", label: "Liebesman, Jonathan"},
    {value: "Kevin Lima", label: "Lima, Kevin"},
    {value: "Doug Liman", label: "Liman, Doug"},
    {value: "Justin Lin", label: "Lin, Justin"},
    {value: "Richard Linklater", label: "Linklater, Richard"},
    {value: "Phil Lord & Christopher Miller", label: "Lord, Phil & Miller, Christopher"},
    {value: "David Lowery", label: "Lowery, David"},
    {value: "George Lucas", label: "Lucas, George"},
    {value: "Jon Lucas", label: "Lucas, Jon"},
    {value: "Baz Luhrmann", label: "Luhrmann, Baz"},
    {value: "Robert Luketic", label: "Luketic, Robert"},
    {value: "Kevin Macdonald", label: "Macdonald, Kevin"},
    {value: "John Madden", label: "Madden, John"},
    {value: "Terrence Malick", label: "Malick, Terrence"},
    {value: "James Mangold", label: "Mangold, James"},
    {value: "Michael Mann", label: "Mann, Michael"},
    {value: "Garry Marshall", label: "Marshall, Garry"},
    {value: "Neil Marshall", label: "Marshall, Neil"},
    {value: "Penny Marshall", label: "Marshall, Penny"},
    {value: "Rob Marshall", label: "Marshall, Rob"},
    {value: "Les Mayfield", label: "Mayfield, Les"},
    {value: "Tom McCarthy", label: "McCarthy, Tom"},
    {value: "Martin McDonagh", label: "McDonagh, Martin"},
    {value: "McG ", label: "McG"},
    {value: "Paul McGuigan", label: "McGuigan, Paul"},
    {value: "Adam McKay", label: "McKay, Adam"},
    {value: "Sean McNamara", label: "McNamara, Sean"},
    {value: "Christopher McQuarrie", label: "McQuarrie, Christopher"},
    {value: "Steve McQueen", label: "McQueen, Steve"},
    {value: "James McTeigue", label: "McTeigue, James"},
    {value: "John McTiernan", label: "McTiernan, John"},
    {value: "Olivier Megaton", label: "Megaton, Olivier"},
    {value: "Fernando Meirelles", label: "Meirelles, Fernando"},
    {value: "Sam Mendes", label: "Mendes, Sam"},
    {value: "Nancy Meyers", label: "Meyers, Nancy"},
    {value: "Roger Michell", label: "Michell, Roger"},
    {value: "David Michôd", label: "Michôd, David"},
    {value: "Bennett Miller", label: "Miller, Bennett"},
    {value: "Frank Miller", label: "Miller, Frank"},
    {value: "George Miller", label: "Miller, George"},
    {value: "Steve Miner", label: "Miner, Steve"},
    {value: "Rob Minkoff", label: "Minkoff, Rob"},
    {value: "Mike Mitchell", label: "Mitchell, Mike"},
    {value: "Hayao Miyazaki", label: "Miyazaki, Hayao"},
    {value: "John Moore", label: "Moore, John"},
    {value: "Pierre Morel", label: "Morel, Pierre"},
    {value: "Jonathan Mostow", label: "Mostow, Jonathan"},
    {value: "Greg Mottola", label: "Mottola, Greg"},
    {value: "Gabriele Muccino", label: "Muccino, Gabriele"},
    {value: "Andy Muschietti", label: "Muschietti, Andy"},
    {value: "Mira Nair", label: "Nair, Mira"},
    {value: "Mike Newell", label: "Newell, Mike"},
    {value: "Andrew Niccol", label: "Niccol, Andrew"},
    {value: "Jeff Nichols", label: "Nichols, Jeff"},
    {value: "Leonard Nimoy", label: "Nimoy, Leonard"},
    {value: "Marcus Nispel", label: "Nispel, Marcus"},
    {value: "Christopher Nolan", label: "Nolan, Christopher"},
    {value: "Phillip Noyce", label: "Noyce, Phillip"},
    {value: "Gavin O'Connor", label: "O'Connor, Gavin"},
    {value: "Steve Oedekerk", label: "Oedekerk, Steve"},
    {value: "Kenny Ortega", label: "Ortega, Kenny"},
    {value: "Frank Oz", label: "Oz, Frank"},
    {value: "Alan J. Pakula", label: "Pakula, Alan J."},
    {value: "Pawel Pawlikowski", label: "Pawlikowski, Pawel"},
    {value: "Alexander Payne", label: "Payne, Alexander"},
    {value: "Jesse Peretz", label: "Peretz, Jesse"},
    {value: "Tyler Perry", label: "Perry, Tyler"},
    {value: "Wolfgang Peterson", label: "Peterson, Wolfgang"},
    {value: "Donald Petrie", label: "Petrie, Donald"},
    {value: "Brad Peyton", label: "Peyton, Brad"},
    {value: "Todd Phillips", label: "Phillips, Todd"},
    {value: "Steve Pink", label: "Pink, Steve"},
    {value: "Roman Polanski", label: "Polanski, Roman"},
    {value: "Gina Prince-Bythewood", label: "Prince-Bythewood, Gina"},
    {value: "Sam Raimi", label: "Raimi, Sam"},
    {value: "Harold Ramis", label: "Ramis, Harold"},
    {value: "Brett Ratner", label: "Ratner, Brett"},
    {value: "Robert Redford", label: "Redford, Robert"},
    {value: "Peyton Reed", label: "Reed, Peyton"},
    {value: "Dee Rees", label: "Rees, Dee"},
    {value: "Matt Reeves", label: "Reeves, Matt"},
    {value: "Nicolas Winding Refn", label: "Refn, Nicolas Winding"},
    {value: "Rob Reiner", label: "Reiner, Rob"},
    {value: "Wolfgang Reitherman", label: "Reitherman, Wolfgang"},
    {value: "Ivan Reitman", label: "Reitman, Ivan"},
    {value: "Jason Reitman", label: "Reitman, Jason"},
    {value: "Chris Renaud", label: "Renaud, Chris"},
    {value: "John Requa", label: "Requa, John"},
    {value: "Kevin Reynolds", label: "Reynolds, Kevin"},
    {value: "Guy Ritchie", label: "Ritchie, Guy"},
    {value: "Michael Ritchie", label: "Ritchie, Michael"},
    {value: "Jay Roach", label: "Roach, Jay"},
    {value: "Brian Robbins", label: "Robbins, Brian"},
    {value: "Johannes Roberts", label: "Roberts, Johannes"},
    {value: "Phil Alden Robinson", label: "Robinson, Phil Alden"},
    {value: "Todd Robinson", label: "Robinson, Todd"},
    {value: "Chris Rock", label: "Rock, Chris"},
    {value: "Robert Rodriguez", label: "Rodriguez, Robert"},
    {value: "Gary Ross", label: "Ross, Gary"},
    {value: "Eli Roth", label: "Roth, Eli"},
    {value: "Chuck Russell", label: "Russell, Chuck"},
    {value: "David O. Russell", label: "Russell, David O."},
    {value: "Anthony Russo & Joe Russo", label: "Russo, Anthony & Russo, Joe"},
    {value: "Carlos Saldanha", label: "Saldanha, Carlos"},
    {value: "David F. Sandberg", label: "Sandberg, David F."},
    {value: "Akiva Schaffer", label: "Schaffer, Akiva"},
    {value: "John Schultz", label: "Schultz, John"},
    {value: "Joel Schumacher", label: "Schumacher, Joel"},
    {value: "Robert Schwentke", label: "Schwentke, Robert"},
    {value: "Martin Scorsese", label: "Scorsese, Martin"},
    {value: "Ridley Scott", label: "Scott, Ridley"},
    {value: "Tony Scott", label: "Scott, Tony"},
    {value: "Peter Segal", label: "Segal, Peter"},
    {value: "Dominic Sena", label: "Sena, Dominic"},
    {value: "Tom Shadyac", label: "Shadyac, Tom"},
    {value: "Adam Shankman", label: "Shankman, Adam"},
    {value: "Lynn Shelton", label: "Shelton, Lynn"},
    {value: "Ron Shelton", label: "Shelton, Ron"},
    {value: "M. Night Shyamalan", label: "Shyamalan, M. Night"},
    {value: "Brad Silberling", label: "Silberling, Brad"},
    {value: "Bryan Singer", label: "Singer, Bryan"},
    {value: "Tarsem Singh", label: "Singh, Tarsem"},
    {value: "Charles Martin Smith", label: "Smith, Charles Martin"},
    {value: "Kevin Smith", label: "Smith, Kevin"},
    {value: "Zack Snyder", label: "Snyder, Zack"},
    {value: "Steven Soderbergh", label: "Soderbergh, Steven"},
    {value: "Stephen Sommers", label: "Sommers, Stephen"},
    {value: "Barry Sonnenfeld", label: "Sonnenfeld, Barry"},
    {value: "Steven Spielberg", label: "Spielberg, Steven"},
    {value: "Michael Spierig & Peter Spierig", label: "Spierig, Michael & Spierig, Peter"},
    {value: "Chad Stahleski", label: "Stahleski, Chad"},
    {value: "Sylvester Stallone", label: "Stallone, Sylvester"},
    {value: "Andrew Stanton", label: "Stanton, Andrew"},
    {value: "Burr Steers", label: "Steers, Burr"},
    {value: "Scott Stewart", label: "Stewart, Scott"},
    {value: "Ben Stiller", label: "Stiller, Ben"},
    {value: "Nicholas Stoller", label: "Stoller, Nicholas"},
    {value: "Oliver Stone", label: "Stone, Oliver"},
    {value: "Tim Story", label: "Story, Tim"},
    {value: "Todd Strauss-Schulson", label: "Strauss-Schulson, Todd"},
    {value: "David E. Talbert", label: "Talbert, David E."},
    {value: "Lee Tamahori", label: "Tamahori, Lee"},
    {value: "Quentin Tarantino", label: "Tarantino, Quentin"},
    {value: "Genndy Tartakovsky", label: "Tartakovsky, Genndy"},
    {value: "Deon Taylor", label: "Taylor, Deon"},
    {value: "Tate Taylor", label: "Taylor, Tate"},
    {value: "Sam Taylor-Johnson", label: "Taylor-Johnson, Sam"},
    {value: "Andy Tennant", label: "Tennant, Andy"},
    {value: "Betty Thomas", label: "Thomas, Betty"},
    {value: "Rawson Marshall Thurber", label: "Thurber, Rawson Marshall"},
    {value: "Michael Tiddes", label: "Tiddes, Michael"},
    {value: "George Tillman Jr.", label: "Tillman Jr., George"},
    {value: "Josh Trank", label: "Trank, Josh"},
    {value: "Jeff Tremaine", label: "Tremaine, Jeff"},
    {value: "Colin Trevorrow", label: "Trevorrow, Colin"},
    {value: "Gary Trousdale", label: "Trousdale, Gary"},
    {value: "Jon Turteltaub", label: "Turteltaub, Jon"},
    {value: "Ron Underwood", label: "Underwood, Ron"},
    {value: "Jean-Marc Vallée", label: "Vallée, Jean-Marc"},
    {value: "Gus Van Sant", label: "Van Sant, Gus"},
    {value: "Tom Vaughan", label: "Vaughan, Tom"},
    {value: "Matthew Vaughn", label: "Vaughn, Matthew"},
    {value: "Gore Verbinski", label: "Verbinski, Gore"},
    {value: "Paul Verhoeven", label: "Verhoeven, Paul"},
    {value: "Denis Villeneuve", label: "Villeneuve, Denis"},
    {value: "Lana Wachowski & Lilly Wachowski", label: "Wachowski, Lana & Wachowski, Lilly"},
    {value: "Jeff Wadlow", label: "Wadlow, Jeff"},
    {value: "David Wain", label: "Wain, David"},
    {value: "Taika Waititi", label: "Waititi, Taika"},
    {value: "James Wan", label: "Wan, James"},
    {value: "David S. Ward", label: "Ward, David S."},
    {value: "Mark Waters", label: "Waters, Mark"},
    {value: "Keenen Ivory Wayans", label: "Wayans, Keenen Ivory"},
    {value: "Marc Webb", label: "Webb, Marc"},
    {value: "Chris Wedge", label: "Wedge, Chris"},
    {value: "Peter Weir", label: "Weir, Peter"},
    {value: "Sam Weisman", label: "Weisman, Sam"},
    {value: "Chris Weitz", label: "Weitz, Chris"},
    {value: "Paul Weitz", label: "Weitz, Paul"},
    {value: "Simon West", label: "West, Simon"},
    {value: "Leigh Whannell", label: "Whannell, Leigh"},
    {value: "Joss Whedon", label: "Whedon, Joss"},
    {value: "Sylvain White", label: "White, Sylvain"},
    {value: "John Whitesell", label: "Whitesell, John"},
    {value: "Gary Winick", label: "Winick, Gary"},
    {value: "Len Wiseman", label: "Wiseman, Len"},
    {value: "James Wong", label: "Wong, James"},
    {value: "John Woo", label: "Woo, John"},
    {value: "Edgar Wright", label: "Wright, Edgar"},
    {value: "Joe Wright", label: "Wright, Joe"},
    {value: "Boaz Yakin", label: "Yakin, Boaz"},
    {value: "David Yates", label: "Yates, David"},
    {value: "Terence Young", label: "Young, Terence"},
    {value: "Ronny Yu", label: "Yu, Ronny"},
    {value: "Robert Zemeckis", label: "Zemeckis, Robert"},
    {value: "Rob Zombie", label: "Zombie, Rob"},
    {value: "David Zucker", label: "Zucker, David"},
    {value: "Edward Zwick", label: "Zwick, Edward"}
]

export const genreOptions: DropdownOption[] = [
    {value: "Action", label: "Action"},
    {value: "Adventure", label: "Adventure"},
    {value: "Animation", label: "Animation"},
    {value: "Comedy", label: "Comedy"},
    {value: "Crime", label: "Crime"},
    {value: "Disaster", label: "Disaster"},
    {value: "Drama", label: "Drama"},
    {value: "Dramedy", label: "Dramedy"},
    {value: "Family", label: "Family"},
    {value: "Fantasy", label: "Fantasy"},
    {value: "Horror", label: "Horror"},
    {value: "Musical", label: "Musical"},
    {value: "Mystery", label: "Mystery"},
    {value: "Romance", label: "Romance"},
    {value: "Sci-Fi", label: "Sci-Fi"},
]

export const subGenreOptions: DropdownOption[] = [
    {value: "Action Comedy", label: "Action Comedy"},
    {value: "Action Thriller", label: "Action Thriller"},
    {value: "Adult Animation", label: "Adult Animation"},
    {value: "Alien Invasion", label: "Alien Invasion"},
    {value: "Assassins, Hitmen, & Gunslingers", label: "Assassins, Hitmen, & Gunslingers"},
    {value: "BioPic & True Story", label: "BioPic & True Story"},
    {value: "Buddies & Screwballs", label: "Buddies & Screwballs"},
    {value: "Comic", label: "Comic"},
    {value: "Coming-of-Age", label: "Coming-of-Age"},
    {value: "Cooking", label: "Cooking"},
    {value: "Courtroom", label: "Courtroom"},
    {value: "Crime Thriller", label: "Crime Thriller"},
    {value: "Dance & Music", label: "Dance & Music"},
    {value: "Dance & Musice", label: "Dance & Musice"},
    {value: "Dark Comedy", label: "Dark Comedy"},
    {value: "Dark Humor", label: "Dark Humor"},
    {value: "Demons & Possession", label: "Demons & Possession"},
    {value: "Disaster & Apocalypse", label: "Disaster & Apocalypse"},
    {value: "Dystopian", label: "Dystopian"},
    {value: "Family Comedy", label: "Family Comedy"},
    {value: "Family Dynamics", label: "Family Dynamics"},
    {value: "Fast Cars & Getaways", label: "Fast Cars & Getaways"},
    {value: "Gangster, Mafia, & Mob", label: "Gangster, Mafia, & Mob"},
    {value: "Gangster, Mob, & Mafia", label: "Gangster, Mob, & Mafia"},
    {value: "Haunted & Paranormal", label: "Haunted & Paranormal"},
    {value: "Heist", label: "Heist"},
    {value: "Kids & Family", label: "Kids & Family"},
    {value: "LBGTQ+", label: "LBGTQ+"},
    {value: "Mall Cop", label: "Mall Cop"},
    {value: "Mecha & Gundam", label: "Mecha & Gundam"},
    {value: "Melodrama", label: "Melodrama"},
    {value: "Monsters & Creatures", label: "Monsters & Creatures"},
    {value: "Mystery & Suspense", label: "Mystery & Suspense"},
    {value: "Neo-Western", label: "Neo-Western"},
    {value: "Parody, Satire, & Spoof", label: "Parody, Satire, & Spoof"},
    {value: "Police & Detectives", label: "Police & Detectives"},
    {value: "Political", label: "Political"},
    {value: "Post-Apocalypse", label: "Post-Apocalypse"},
    {value: "Psychological Horror", label: "Psychological Horror"},
    {value: "Psychological Thriller", label: "Psychological Thriller"},
    {value: "Raunchy Humor", label: "Raunchy Humor"},
    {value: "Religious", label: "Religious"},
    {value: "Romantic Comedy", label: "Romantic Comedy"},
    {value: "Romantic Drama", label: "Romantic Drama"},
    {value: "Sci-Fi Thriller", label: "Sci-Fi Thriller"},
    {value: "Secret Agents & Espionage", label: "Secret Agents & Espionage"},
    {value: "Slasher, Shock, & Gore", label: "Slasher, Shock, & Gore"},
    {value: "Social & Political Commentary", label: "Social & Political Commentary"},
    {value: "Space Drama", label: "Space Drama"},
    {value: "Space Opera", label: "Space Opera"},
    {value: "Sports", label: "Sports"},
    {value: "Stand-Up", label: "Stand-Up"},
    {value: "Stoner Flick", label: "Stoner Flick"},
    {value: "Sword & Sandal", label: "Sword & Sandal"},
    {value: "Teen Comedy", label: "Teen Comedy"},
    {value: "Teen Scream", label: "Teen Scream"},
    {value: "Video Game", label: "Video Game"},
    {value: "War", label: "War"},
    {value: "Western", label: "Western"},
    {value: "Witches & Wizards", label: "Witches & Wizards"},
    {value: "Young Adult", label: "Young Adult"},
]

export const studiocompanyOptions: DropdownOption[] = [
    {value: "20th Century Studios", label: "20th Century Studios"},
    {value: "A24", label: "A24"},
    {value: "Aardman Animation", label: "Aardman Animation"},
    {value: "Adult Swim", label: "Adult Swim"},
    {value: "Amazon Studios", label: "Amazon Studios"},
    {value: "Annapurna Pictures", label: "Annapurna Pictures"},
    {value: "Avalanche Animation", label: "Avalanche Animation"},
    {value: "Bleecker Street", label: "Bleecker Street"},
    {value: "Blue Sky Animation", label: "Blue Sky Animation"},
    {value: "Blumhouse", label: "Blumhouse"},
    {value: "Cartoon Saloon", label: "Cartoon Saloon"},
    {value: "Crest Animation", label: "Crest Animation"},
    {value: "DC", label: "DC"},
    {value: "Dark Horse", label: "Dark Horse"},
    {value: "Dimension Films", label: "Dimension Films"},
    {value: "Disney", label: "Disney"},
    {value: "DreamWorks Animation", label: "DreamWorks Animation"},
    {value: "DreamWorks Pictures", label: "DreamWorks Pictures"},
    {value: "Focus Features", label: "Focus Features"},
    {value: "HBO Original", label: "HBO Original"},
    {value: "Happy Madison", label: "Happy Madison"},
    {value: "Huhu Animation", label: "Huhu Animation"},
    {value: "Hulu Original", label: "Hulu Original"},
    {value: "Illumination", label: "Illumination"},
    {value: "Laika Animation", label: "Laika Animation"},
    {value: "Lionsgate", label: "Lionsgate"},
    {value: "Lucasfilm", label: "Lucasfilm"},
    {value: "Lucasfilm Animation", label: "Lucasfilm Animation"},
    {value: "MGM Studios", label: "MGM Studios"},
    {value: "Marvel", label: "Marvel"},
    {value: "Netflix Original", label: "Netflix Original"},
    {value: "Nickelodeon", label: "Nickelodeon"},
    {value: "Open Road Animation", label: "Open Road Animation"},
    {value: "Orion Pictures", label: "Orion Pictures"},
    {value: "Paramount Animation", label: "Paramount Animation"},
    {value: "Paramount Pictures", label: "Paramount Pictures"},
    {value: "Rainmaker Animation", label: "Rainmaker Animation"},
    {value: "Reel FX Animation", label: "Reel FX Animation"},
    {value: "STX Animation", label: "STX Animation"},
    {value: "Searchlight Pictures", label: "Searchlight Pictures"},
    {value: "Sony Animation", label: "Sony Animation"},
    {value: "Sony Pictures", label: "Sony Pictures"},
    {value: "Starz Animation", label: "Starz Animation"},
    {value: "Studio Ghibli", label: "Studio Ghibli"},
    {value: "Summit Animation", label: "Summit Animation"},
    {value: "Toho", label: "Toho"},
    {value: "TriStar Animation", label: "TriStar Animation"},
    {value: "Universal Pictures", label: "Universal Pictures"},
    {value: "Warner Bros.", label: "Warner Bros."},
]

export const universeOptions: DropdownOption[] = [
    {value: "A Nightmare on Elm Street", label: "A Nightmare on Elm Street"},
    {value: "Ace Ventura", label: "Ace Ventura"},
    {value: "Adam Sandler-verse", label: "Adam Sandler-verse"},
    {value: "Addams Family", label: "Addams Family"},
    {value: "Alien", label: "Alien"},
    {value: "Alien vs. Predator", label: "Alien vs. Predator"},
    {value: "American Pie", label: "American Pie"},
    {value: "Amityville", label: "Amityville"},
    {value: "Anchroman", label: "Anchroman"},
    {value: "Arthur", label: "Arthur"},
    {value: "Austin Powers", label: "Austin Powers"},
    {value: "Baby Geniuses", label: "Baby Geniuses"},
    {value: "Back to the Future", label: "Back to the Future"},
    {value: "Bad Boys", label: "Bad Boys"},
    {value: "Bad News Bears", label: "Bad News Bears"},
    {value: "Barbershop", label: "Barbershop"},
    {value: "Before Trilogy", label: "Before Trilogy"},
    {value: "Beverly Hills Cop", label: "Beverly Hills Cop"},
    {value: "Bill & Ted", label: "Bill & Ted"},
    {value: "Blade Runner", label: "Blade Runner"},
    {value: "Bourne", label: "Bourne"},
    {value: "Bring It On", label: "Bring It On"},
    {value: "Carrie", label: "Carrie"},
    {value: "Charlie's Angels", label: "Charlie's Angels"},
    {value: "Child's Play", label: "Child's Play"},
    {value: "Cloverfield", label: "Cloverfield"},
    {value: "Conjuring Universe", label: "Conjuring Universe"},
    {value: "Dark Universe", label: "Dark Universe"},
    {value: "DC (DCEU)", label: "DC (DCEU)"},
    {value: "DC (Non-DCEU)", label: "DC (Non-DCEU)"},
    {value: "Death Race", label: "Death Race"},
    {value: "Die Hard", label: "Die Hard"},
    {value: "Dirty Harry", label: "Dirty Harry"},
    {value: "Disney Animated", label: "Disney Animated"},
    {value: "Disney Live-Action", label: "Disney Live-Action"},
    {value: "Dollars Trilogy", label: "Dollars Trilogy"},
    {value: "Dr. Seuss", label: "Dr. Seuss"},
    {value: "Dragon Tattoo Series", label: "Dragon Tattoo Series"},
    {value: "Dragon Tattoo Stories", label: "Dragon Tattoo Stories"},
    {value: "Dumb and Dumber", label: "Dumb and Dumber"},
    {value: "Fallen", label: "Fallen"},
    {value: "Fast & Furious", label: "Fast & Furious"},
    {value: "Fifty Shades", label: "Fifty Shades"},
    {value: "Final Destination", label: "Final Destination"},
    {value: "Friday the 13th", label: "Friday the 13th"},
    {value: "G.I. Joe", label: "G.I. Joe"},
    {value: "Ghostbusters", label: "Ghostbusters"},
    {value: "Gnomes", label: "Gnomes"},
    {value: "Godfather", label: "Godfather"},
    {value: "Gremlins", label: "Gremlins"},
    {value: "Halloween", label: "Halloween"},
    {value: "Hangover Trilogy", label: "Hangover Trilogy"},
    {value: "Hanna-Barbera", label: "Hanna-Barbera"},
    {value: "Hannibal Lecter", label: "Hannibal Lecter"},
    {value: "Happy Death Day", label: "Happy Death Day"},
    {value: "Harold & Kumar", label: "Harold & Kumar"},
    {value: "Hellboy", label: "Hellboy"},
    {value: "Home Alone", label: "Home Alone"},
    {value: "Hot Tub Time Machine", label: "Hot Tub Time Machine"},
    {value: "Hotel Transylvania", label: "Hotel Transylvania"},
    {value: "How To Train Your Dragon", label: "How To Train Your Dragon"},
    {value: "Ice Age", label: "Ice Age"},
    {value: "Indiana Jones", label: "Indiana Jones"},
    {value: "Insidious", label: "Insidious"},
    {value: "It (Pennywise)", label: "It (Pennywise)"},
    {value: "Jack Ryan (Ryanverse)", label: "Jack Ryan (Ryanverse)"},
    {value: "James Bond", label: "James Bond"},
    {value: "Jaws", label: "Jaws"},
    {value: "John Wick", label: "John Wick"},
    {value: "Johnny English", label: "Johnny English"},
    {value: "Jumanji", label: "Jumanji"},
    {value: "Jurassic Park", label: "Jurassic Park"},
    {value: "Kick-Ass", label: "Kick-Ass"},
    {value: "Kung Fu Panda", label: "Kung Fu Panda"},
    {value: "Legally Blonde", label: "Legally Blonde"},
    {value: "LEGO", label: "LEGO"},
    {value: "Lethal Weapon", label: "Lethal Weapon"},
    {value: "Mad Max", label: "Mad Max"},
    {value: "Madagascar", label: "Madagascar"},
    {value: "Major League", label: "Major League"},
    {value: "Mamma Mia!", label: "Mamma Mia!"},
    {value: "Marvel (MCU)", label: "Marvel (MCU)"},
    {value: "Marvel (Non-MCU)", label: "Marvel (Non-MCU)"},
    {value: "Marvel (X-Men)", label: "Marvel (X-Men)"},
    {value: "Marvel (Sony Pictures)", label: "Marvel (Sony Pictures)"},
    {value: "Matrix", label: "Matrix"},
    {value: "Meet the Parents", label: "Meet the Parents"},
    {value: "Men in Black", label: "Men in Black"},
    {value: "Middle-earth", label: "Middle-earth"},
    {value: "Minions", label: "Minions"},
    {value: "Mission: Impossible", label: "Mission: Impossible"},
    {value: "MonsterVerse", label: "MonsterVerse"},
    {value: "Monty Python", label: "Monty Python"},
    {value: "Naked Gun", label: "Naked Gun"},
    {value: "National Lampoon", label: "National Lampoon"},
    {value: "Nicholas Sparks", label: "Nicholas Sparks"},
    {value: "Ninja Turtles", label: "Ninja Turtles"},
    {value: "Ocean's Franchise", label: "Ocean's Franchise"},
    {value: "Ouija", label: "Ouija"},
    {value: "Paranormal Activity", label: "Paranormal Activity"},
    {value: "Pathé Animation", label: "Pathé Animation"},
    {value: "Pitch Perfect", label: "Pitch Perfect"},
    {value: "Planet of the Apes", label: "Planet of the Apes"},
    {value: "PlayStation", label: "PlayStation"},
    {value: "Pokemon", label: "Pokemon"},
    {value: "Predator", label: "Predator"},
    {value: "Public Domain", label: "Public Domain"},
    {value: "Purge", label: "Purge"},
    {value: "Rambo", label: "Rambo"},
    {value: "Resident Evil", label: "Resident Evil"},
    {value: "Ring Series", label: "Ring Series"},
    {value: "Rocky", label: "Rocky"},
    {value: "Rugrats", label: "Rugrats"},
    {value: "Rush Hour", label: "Rush Hour"},
    {value: "Saw", label: "Saw"},
    {value: "Scary Movie", label: "Scary Movie"},
    {value: "Scream", label: "Scream"},
    {value: "Secret Life of Pets", label: "Secret Life of Pets"},
    {value: "Shrek", label: "Shrek"},
    {value: "Sin City", label: "Sin City"},
    {value: "Sinister", label: "Sinister"},
    {value: "Smurfs", label: "Smurfs"},
    {value: "SpongeBob", label: "SpongeBob"},
    {value: "Spy Kids", label: "Spy Kids"},
    {value: "Star Trek", label: "Star Trek"},
    {value: "Star Wars", label: "Star Wars"},
    {value: "Teen Wolf", label: "Teen Wolf"},
    {value: "Terminator", label: "Terminator"},
    {value: "Texas Chain Saw", label: "Texas Chain Saw"},
    {value: "Three Flavours Cornetto", label: "Three Flavours Cornetto"},
    {value: "Transformers", label: "Transformers"},
    {value: "Transporter", label: "Transporter"},
    {value: "Trolls", label: "Trolls"},
    {value: "Twilight", label: "Twilight"},
    {value: "Tyler Perry-verse", label: "Tyler Perry-verse"},
    {value: "Unbreakable Trilogy", label: "Unbreakable Trilogy"},
    {value: "Unfriended", label: "Unfriended"},
    {value: "View Askewniverse", label: "View Askewniverse"},
    {value: "Wizarding World", label: "Wizarding World"},
    {value: "Zorro", label: "Zorro"},
    {value: "xXx", label: "xXx"},
]

export const subUniverseOptions: DropdownOption[] = [
    {value: "Disney Animation Studios", label: "Disney Animation Studios"},
    {value: "Disney Live-Action Remake", label: "Disney Live-Action Remake"},
    {value: "Fantastic Beasts", label: "Fantastic Beasts"},
    {value: "Harry Potter", label: "Harry Potter"},
    {value: "Hobbit", label: "Hobbit"},
    {value: "Honey, I Shrunk", label: "Honey, I Shrunk"},
    {value: "James Bond - Brosnan", label: "James Bond - Brosnan"},
    {value: "James Bond - Connery", label: "James Bond - Connery"},
    {value: "James Bond - Craig", label: "James Bond - Craig"},
    {value: "James Bond - Dalton", label: "James Bond - Dalton"},
    {value: "James Bond - Lazenby", label: "James Bond - Lazenby"},
    {value: "James Bond - Moore", label: "James Bond - Moore"},
    {value: "Jurassic Original", label: "Jurassic Original"},
    {value: "Jurassic Sequel", label: "Jurassic Sequel"},
    {value: "Lord of the Rings", label: "Lord of the Rings"},
    {value: "Mary Poppins", label: "Mary Poppins"},
    {value: "Mighty Ducks", label: "Mighty Ducks"},
    {value: "Mummy", label: "Mummy"},
    {value: "Muppets", label: "Muppets"},
    {value: "Narnia", label: "Narnia"},
    {value: "Pirates of the Caribbean", label: "Pirates of the Caribbean"},
    {value: "Pixar", label: "Pixar"},
    {value: "Planet of the Apes New", label: "Planet of the Apes New"},
    {value: "Planet of the Apes Old", label: "Planet of the Apes Old"},
    {value: "Planet of the Apes Reboot", label: "Planet of the Apes Reboot"},
    {value: "Star Trek Kelvin", label: "Star Trek Kelvin"},
    {value: "Star Trek Next Generation", label: "Star Trek Next Generation"},
    {value: "Star Trek Original Series", label: "Star Trek Original Series"},
    {value: "Star Wars Original", label: "Star Wars Original"},
    {value: "Star Wars Prequel", label: "Star Wars Prequel"},
    {value: "Star Wars Sequel", label: "Star Wars Sequel"},
    {value: "Star Wars Standalone", label: "Star Wars Standalone"},
    {value: "Transformers Michael Bay", label: "Transformers Michael Bay"},
    {value: "Transformers Standalone", label: "Transformers Standalone"},
    {value: "Tron", label: "Tron"},
    {value: "Vacation", label: "Vacation"},
]

export const characterOptions: DropdownOption[] = [
    {value: "Adam Sandler", label: "Adam Sandler"},
    {value: "Ant-Man", label: "Ant-Man"},
    {value: "Aquaman", label: "Aquaman"},
    {value: "Avengers", label: "Avengers"},
    {value: "Batman", label: "Batman"},
    {value: "Black Panther", label: "Black Panther"},
    {value: "Blade", label: "Blade"},
    {value: "Captain America", label: "Captain America"},
    {value: "Captain Marvel", label: "Captain Marvel"},
    {value: "Cat in the Hat", label: "Cat in the Hat"},
    {value: "Catwoman", label: "Catwoman"},
    {value: "Chucky", label: "Chucky"},
    {value: "Constantine", label: "Constantine"},
    {value: "Creed", label: "Creed"},
    {value: "Daredevil", label: "Daredevil"},
    {value: "Deadpool", label: "Deadpool"},
    {value: "Doctor Strange", label: "Doctor Strange"},
    {value: "Dracula", label: "Dracula"},
    {value: "Elektra", label: "Elektra"},
    {value: "Fantastic Four", label: "Fantastic Four"},
    {value: "Freddy Krueger", label: "Freddy Krueger"},
    {value: "Ghost Rider", label: "Ghost Rider"},
    {value: "Godzilla", label: "Godzilla"},
    {value: "Green Lantern", label: "Green Lantern"},
    {value: "Grinch", label: "Grinch"},
    {value: "Guardians of the Galaxy", label: "Guardians of the Galaxy"},
    {value: "Harley Quinn", label: "Harley Quinn"},
    {value: "Hellboy", label: "Hellboy"},
    {value: "Howard the Duck", label: "Howard the Duck"},
    {value: "Hulk", label: "Hulk"},
    {value: "Indiana Jones", label: "Indiana Jones"},
    {value: "Iron Man", label: "Iron Man"},
    {value: "Jason Voorhees", label: "Jason Voorhees"},
    {value: "Jaws", label: "Jaws"},
    {value: "Jigsaw", label: "Jigsaw"},
    {value: "Johnny English", label: "Johnny English"},
    {value: "Joker", label: "Joker"},
    {value: "Jonah Hex", label: "Jonah Hex"},
    {value: "Justice League", label: "Justice League"},
    {value: "King Kong", label: "King Kong"},
    {value: "Leatherface", label: "Leatherface"},
    {value: "Man with No Name", label: "Man with No Name"},
    {value: "Michael Myers", label: "Michael Myers"},
    {value: "Mummy", label: "Mummy"},
    {value: "Pee-wee", label: "Pee-wee"},
    {value: "Pennywise", label: "Pennywise"},
    {value: "Predator", label: "Predator"},
    {value: "Punisher", label: "Punisher"},
    {value: "Rambo", label: "Rambo"},
    {value: "Rocky Balboa", label: "Rocky Balboa"},
    {value: "Ron Burgundy", label: "Ron Burgundy"},
    {value: "Scooby-Doo", label: "Scooby-Doo"},
    {value: "Shazam!", label: "Shazam!"},
    {value: "Shrek", label: "Shrek"},
    {value: "Simpsons", label: "Simpsons"},
    {value: "Spider-Man", label: "Spider-Man"},
    {value: "Suicide Squad", label: "Suicide Squad"},
    {value: "Supergirl", label: "Supergirl"},
    {value: "Superman", label: "Superman"},
    {value: "Swamp Thing", label: "Swamp Thing"},
    {value: "Thor", label: "Thor"},
    {value: "Van Helsing", label: "Van Helsing"},
    {value: "Venom", label: "Venom"},
    {value: "Willy Wonka", label: "Willy Wonka"},
    {value: "Wolfman", label: "Wolfman"},
    {value: "Wolverine", label: "Wolverine"},
    {value: "Wonder Woman", label: "Wonder Woman"},
    {value: "X-Men", label: "X-Men"},
    {value: "Xander Cage", label: "Xander Cage"},
]

export const sportholidayOptions: DropdownOption[] = [
    {value: "Baseball", label: "Baseball"},
    {value: "Basketball", label: "Basketball"},
    {value: "Billiards", label: "Billiards"},
    {value: "Bowling", label: "Bowling"},
    {value: "Boxing", label: "Boxing"},
    {value: "Cheerleading", label: "Cheerleading"},
    {value: "Chess", label: "Chess"},
    {value: "Christmas", label: "Christmas"},
    {value: "Dodgeball", label: "Dodgeball"},
    {value: "Football", label: "Football"},
    {value: "Golf", label: "Golf"},
    {value: "Hockey", label: "Hockey"},
    {value: "Horse Racing", label: "Horse Racing"},
    {value: "Martial Arts", label: "Martial Arts"},
    {value: "Olympics", label: "Olympics"},
    {value: "Point Break", label: "Point Break"},
    {value: "Poker", label: "Poker"},
    {value: "Racing", label: "Racing"},
    {value: "Rugby", label: "Rugby"},
    {value: "Soccer", label: "Soccer"},
    {value: "Surfing", label: "Surfing"},
    {value: "Table Tennis", label: "Table Tennis"},
    {value: "Tennis", label: "Tennis"},
    {value: "Volleyball", label: "Volleyball"},
    {value: "Wrestling", label: "Wrestling"},
]

export const yearOptions: DropdownOption[] = [
    {value: "1937", label: "1937"},
    {value: "1939", label: "1939"},
    {value: "1940", label: "1940"},
    {value: "1941", label: "1941"},
    {value: "1942", label: "1942"},
    {value: "1946", label: "1946"},
    {value: "1947", label: "1947"},
    {value: "1949", label: "1949"},
    {value: "1950", label: "1950"},
    {value: "1951", label: "1951"},
    {value: "1952", label: "1952"},
    {value: "1953", label: "1953"},
    {value: "1955", label: "1955"},
    {value: "1956", label: "1956"},
    {value: "1959", label: "1959"},
    {value: "1960", label: "1960"},
    {value: "1961", label: "1961"},
    {value: "1962", label: "1962"},
    {value: "1963", label: "1963"},
    {value: "1964", label: "1964"},
    {value: "1965", label: "1965"},
    {value: "1966", label: "1966"},
    {value: "1967", label: "1967"},
    {value: "1968", label: "1968"},
    {value: "1969", label: "1969"},
    {value: "1970", label: "1970"},
    {value: "1971", label: "1971"},
    {value: "1972", label: "1972"},
    {value: "1973", label: "1973"},
    {value: "1974", label: "1974"},
    {value: "1975", label: "1975"},
    {value: "1976", label: "1976"},
    {value: "1977", label: "1977"},
    {value: "1978", label: "1978"},
    {value: "1979", label: "1979"},
    {value: "1980", label: "1980"},
    {value: "1981", label: "1981"},
    {value: "1982", label: "1982"},
    {value: "1983", label: "1983"},
    {value: "1984", label: "1984"},
    {value: "1985", label: "1985"},
    {value: "1986", label: "1986"},
    {value: "1987", label: "1987"},
    {value: "1988", label: "1988"},
    {value: "1989", label: "1989"},
    {value: "1990", label: "1990"},
    {value: "1991", label: "1991"},
    {value: "1992", label: "1992"},
    {value: "1993", label: "1993"},
    {value: "1994", label: "1994"},
    {value: "1995", label: "1995"},
    {value: "1996", label: "1996"},
    {value: "1997", label: "1997"},
    {value: "1998", label: "1998"},
    {value: "1999", label: "1999"},
    {value: "2000", label: "2000"},
    {value: "2001", label: "2001"},
    {value: "2002", label: "2002"},
    {value: "2003", label: "2003"},
    {value: "2004", label: "2004"},
    {value: "2005", label: "2005"},
    {value: "2006", label: "2006"},
    {value: "2007", label: "2007"},
    {value: "2008", label: "2008"},
    {value: "2009", label: "2009"},
    {value: "2010", label: "2010"},
    {value: "2011", label: "2011"},
    {value: "2012", label: "2012"},
    {value: "2013", label: "2013"},
    {value: "2014", label: "2014"},
    {value: "2015", label: "2015"},
    {value: "2016", label: "2016"},
    {value: "2017", label: "2017"},
    {value: "2018", label: "2018"},
    {value: "2019", label: "2019"},
    {value: "2020", label: "2020"},
]

export const decadeOptions: DropdownOption[] = [
    {value: "1930-1939", label: "1930-1939"},
    {value: "1940-1949", label: "1940-1949"},
    {value: "1950-1959", label: "1950-1959"},
    {value: "1960-1969", label: "1960-1969"},
    {value: "1970-1979", label: "1970-1979"},
    {value: "1980-1989", label: "1980-1989"},
    {value: "1990-1999", label: "1990-1999"},
    {value: "2000-2009", label: "2000-2009"},
    {value: "2010-2019", label: "2010-2019"},
    {value: "2020-2029", label: "2020-2029"},
]

export const provider_names: {[key:string]: string} = {
    "9": "Amazon (Stream)",
    "78": "CBS",
    "337": "Disney+",
    "27@31": "HBO",
    "384": "HBO Max",
    "15": "Hulu",
    "8": "Netflix",
    "386": "Peacock",
    "387": "Peacock Premium",
    "37": "Showtime",
    "43": "Starz",
    "10": "Amazon (Buy/Rent)",
    "2": "Apple",
    "3": "Google",
    "192": "YouTube",
}

const streamingOptions: DropdownOption[] = [
    {value: "9", label: "Amazon (Stream)"},
    {value: "78", label: "CBS"},
    {value: "337", label: "Disney+"},
    {value: "27@31", label: "HBO"},
    {value: "384", label: "HBO Max"},
    {value: "15", label: "Hulu"},
    {value: "8", label: "Netflix"},
    {value: "386", label: "Peacock"},
    {value: "387", label: "Peacock Premium"},
    {value: "37", label: "Showtime"},
    {value: "43", label: "Starz"},
]

const buyrentOptions: DropdownOption[] = [
    {value: "10", label: "Amazon (Buy/Rent)"},
    {value: "2", label: "Apple"},
    {value: "3", label: "Google"},
    {value: "192", label: "YouTube"},
]

export const providerOptions: object[] = [
    {
        label: 'Streaming',
        options: streamingOptions.map(({value, label}) => {
            return {value: value, label: <span className="filter-flex">{label} <img className="filter-icon" src={require(`../media/providers/${value !== '27@31'? value : 27}.png`)} alt={value}/></span>}
        }),
    },
    {
        label: 'Buy/Rent',
        options: buyrentOptions.map(({value, label}) => {
            return {value: value, label: <span className="filter-flex">{label} <img className="filter-icon" src={require(`../media/providers/${value}.png`)} alt={value}/></span>}
        }),
    },
]

const oscarOptions: DropdownOption[] = [
    {value: "Best Picture (Nominated)", label: "Best Picture (Nominated)"},
    {value: "Best Picture (Winner)", label: <span className="filter-flex">Best Picture (Winner) <img className="filter-icon" src={require(`../media/oscars_logo.png`)} alt={'test'}/></span>},
]

const globesOptions: DropdownOption[] = [
    {value: "Best Picture: Drama (Nomination)", label: "Best Picture: Drama (Nomination)"},
    {value: "Best Picture: Drama (Winner)", label: <span className="filter-flex">Best Picture: Drama (Winner) <img className="filter-icon" src={require(`../media/globes_logo.png`)} alt={'test'}/></span>},
    {value: "Best Picture: Musical or Comedy (Nominated)", label: "Best Picture: Musical or Comedy (Nominated)"},
    {value: "Best Picture: Musical or Comedy (Winner)", label: <span className="filter-flex">Best Picture: Musical or Comedy (Winner) <img className="filter-icon" src={require(`../media/globes_logo.png`)} alt={'test'}/></span>},
]

export const awardOptions: object[] = [
    {
        label: 'Oscars',
        options: oscarOptions,
    },
    {
        label: 'Golden Globes',
        options: globesOptions,
    },
]

export const ratingOptions: DropdownOption[] = [
    {value: "avg", label: <span className="filter-flex">Average <img className="filter-icon" src={require(`../media/average.png`)} alt={'test'}/></span>},
    {value: "jeff", label: <span className="filter-flex">Jeff D. Lowe <img className="filter-icon" src={require(`../media/jdl.png`)} alt={'test'}/></span>},
    {value: "kenjac", label: <span className="filter-flex">KenJac <img className="filter-icon" src={require(`../media/kenjac.png`)} alt={'test'}/></span>}
]

export const sortOptions: DropdownOption[] = [
    {value: "ASC", label: "Rating High to Low"},
    {value: "DESC", label: "Rating Low to High"}
]