import React from 'react'

type DropdownOption = { value: string; label: string | JSX.Element }

export const directorOptions: DropdownOption[] = [
  {value: "Jim Abrahams", label: "Abrahams, Jim"},
  {value: "J.J. Abrams", label: "Abrams, J.J."},
  {value: "Ben Affleck", label: "Affleck, Ben"},
  {value: "Alexandre Aja", label: "Aja, Alexandre"},
  {value: "Woody Allen", label: "Allen, Woody"},
  {value: "Robert Altman", label: "Altman, Robert"},
  {value: "Fede Alvarez", label: "Alvarez, Fede"},
  {value: "Jon Amiel", label: "Amiel, Jon"},
  {value: "Sean Anders", label: "Anders, Sean"},
  {value: "Brad Anderson", label: "Anderson, Brad"},
  {value: "Paul Thomas Anderson", label: "Anderson, Paul Thomas"},
  {value: "Paul W.S. Anderson", label: "Anderson, Paul W.S."},
  {value: "Wes Anderson", label: "Anderson, Wes"},
  {value: "Nimród Antal", label: "Antal, Nimród"},
  {value: "Judd Apatow", label: "Apatow, Judd"},
  {value: "Michael Apted", label: "Apted, Michael"},
  {value: "Dario Argento", label: "Argento, Dario"},
  {value: "Darren Aronofsky", label: "Aronofsky, Darren"},
  {value: "Miguel Arteta", label: "Arteta, Miguel"},
  {value: "Kelly Asbury", label: "Asbury, Kelly"},
  {value: "Richard Attenborough", label: "Attenborough, Richard"},
  {value: "John G. Avildsen", label: "Avildsen, John G."},
  {value: "Jon Avnet", label: "Avnet, Jon"},
  {value: "David Ayer", label: "Ayer, David"},
  {value: "John Badham", label: "Badham, John"},
  {value: "Jeff Baena", label: "Baena, Jeff"},
  {value: "Wes Ball", label: "Ball, Wes"},
  {value: "Elizabeth Banks", label: "Banks, Elizabeth"},
  {value: "Daniel Barnz", label: "Barnz, Daniel"},
  {value: "Andrzej Bartkowiak", label: "Bartkowiak, Andrzej"},
  {value: "Noah Baumbach", label: "Baumbach, Noah"},
  {value: "Michael Bay", label: "Bay, Michael"},
  {value: "J.A. Bayona", label: "Bayona, J.A."},
  {value: "Walt Becker", label: "Becker, Walt"},
  {value: "Greg Beeman", label: "Beeman, Greg"},
  {value: "Timur Bekmambetov", label: "Bekmambetov, Timur"},
  {value: "William Brent Bell", label: "Bell, William Brent"},
  {value: "Richard Benjamin", label: "Benjamin, Richard"},
  {value: "Peter Berg", label: "Berg, Peter"},
  {value: "Luc Besson", label: "Besson, Luc"},
  {value: "Thomas Bezucha", label: "Bezucha, Thomas"},
  {value: "Kathryn Bigelow", label: "Bigelow, Kathryn"},
  {value: "Brad Bird", label: "Bird, Brad"},
  {value: "Shane Black", label: "Black, Shane"},
  {value: "Don Bluth", label: "Bluth, Don"},
  {value: "James Bobin", label: "Bobin, James"},
  {value: "Jan de Bont", label: "Bont, Jan de"},
  {value: "Josh Boone", label: "Boone, Josh"},
  {value: "John Boorman", label: "Boorman, John"},
  {value: "David Bowers", label: "Bowers, David"},
  {value: "Rob Bowman", label: "Bowman, Rob"},
  {value: "Danny Boyle", label: "Boyle, Danny"},
  {value: "Steve Boyum", label: "Boyum, Steve"},
  {value: "Tom Brady", label: "Brady, Tom"},
  {value: "Zach Braff", label: "Braff, Zach"},
  {value: "Kenneth Branagh", label: "Branagh, Kenneth"},
  {value: "Martin Brest", label: "Brest, Martin"},
  {value: "Craig Brewer", label: "Brewer, Craig"},
  {value: "Patrick Brice", label: "Brice, Patrick"},
  {value: "Steven Brill", label: "Brill, Steven"},
  {value: "James L. Brooks", label: "Brooks, James L."},
  {value: "Mel Brooks", label: "Brooks, Mel"},
  {value: "Coen Brothers", label: "Brothers, Coen"},
  {value: "Neil Burger", label: "Burger, Neil"},
  {value: "Tim Burton", label: "Burton, Tim"},
  {value: "Mike Cahill", label: "Cahill, Mike"},
  {value: "Christopher Cain", label: "Cain, Christopher"},
  {value: "James Cameron", label: "Cameron, James"},
  {value: "Martin Campbell", label: "Campbell, Martin"},
  {value: "Joe Carnahan", label: "Carnahan, Joe"},
  {value: "John Carney", label: "Carney, John"},
  {value: "Niki Caro", label: "Caro, Niki"},
  {value: "John Carpenter", label: "Carpenter, John"},
  {value: "Steve Carr", label: "Carr, Steve"},
  {value: "Thomas Carter", label: "Carter, Thomas"},
  {value: "D.J. Caruso", label: "Caruso, D.J."},
  {value: "Nick Cassavetes", label: "Cassavetes, Nick"},
  {value: "Nick Castle", label: "Castle, Nick"},
  {value: "Michael Caton-Jones", label: "Caton-Jones, Michael"},
  {value: "J.C. Chandor", label: "Chandor, J.C."},
  {value: "Jay Chandrasekhar", label: "Chandrasekhar, Jay"},
  {value: "Larry Charles", label: "Charles, Larry"},
  {value: "Damien Chazelle", label: "Chazelle, Damien"},
  {value: "Peter Chelsom", label: "Chelsom, Peter"},
  {value: "John Cherry", label: "Cherry, John"},
  {value: "Jon M. Chu", label: "Chu, Jon M."},
  {value: "Derek Cianfrance", label: "Cianfrance, Derek"},
  {value: "Bob Clark", label: "Clark, Bob"},
  {value: "Ron Clements", label: "Clements, Ron"},
  {value: "George Clooney", label: "Clooney, George"},
  {value: "Rob Cohen", label: "Cohen, Rob"},
  {value: "Jaume Collet-Serra", label: "Collet-Serra, Jaume"},
  {value: "Chris Columbus", label: "Columbus, Chris"},
  {value: "Bill Condon", label: "Condon, Bill"},
  {value: "Ryan Coogler", label: "Coogler, Ryan"},
  {value: "Scott Cooper", label: "Cooper, Scott"},
  {value: "Francis Ford Coppola", label: "Coppola, Francis Ford"},
  {value: "Sofia Coppola", label: "Coppola, Sofia"},
  {value: "Frank Coraci", label: "Coraci, Frank"},
  {value: "Don Coscarelli", label: "Coscarelli, Don"},
  {value: "George P. Cosmatos", label: "Cosmatos, George P."},
  {value: "Wes Craven", label: "Craven, Wes"},
  {value: "Destin Daniel Cretton", label: "Cretton, Destin Daniel"},
  {value: "David Cronenberg", label: "Cronenberg, David"},
  {value: "Cameron Crowe", label: "Crowe, Cameron"},
  {value: "John Crowley", label: "Crowley, John"},
  {value: "Alfonso Cuarón", label: "Cuarón, Alfonso"},
  {value: "George Cukor", label: "Cukor, George"},
  {value: "Richard Curtis", label: "Curtis, Richard"},
  {value: "Simon Curtis", label: "Curtis, Simon"},
  {value: "Stephen Daldry", label: "Daldry, Stephen"},
  {value: "Rod Daniel", label: "Daniel, Rod"},
  {value: "Lee Daniels", label: "Daniels, Lee"},
  {value: "Joe Dante", label: "Dante, Joe"},
  {value: "Frank Darabont", label: "Darabont, Frank"},
  {value: "Eric Darnell", label: "Darnell, Eric"},
  {value: "Andrew Davis", label: "Davis, Andrew"},
  {value: "Tamra Davis", label: "Davis, Tamra"},
  {value: "Dean DeBlois", label: "DeBlois, Dean"},
  {value: "James DeMonaco", label: "DeMonaco, James"},
  {value: "Danny DeVito", label: "DeVito, Danny"},
  {value: "Jonathan Demme", label: "Demme, Jonathan"},
  {value: "Ted Demme", label: "Demme, Ted"},
  {value: "Scott Derrickson", label: "Derrickson, Scott"},
  {value: "Howard Deutch", label: "Deutch, Howard"},
  {value: "Tom Dey", label: "Dey, Tom"},
  {value: "Mark A.Z. Dippé", label: "Dippé, Mark A.Z."},
  {value: "Walt Disney", label: "Disney, Walt"},
  {value: "David Dobkin", label: "Dobkin, David"},
  {value: "Pete Docter", label: "Docter, Pete"},
  {value: "Roger Donaldson", label: "Donaldson, Roger"},
  {value: "Richard Donner", label: "Donner, Richard"},
  {value: "Michael Dougherty", label: "Dougherty, Michael"},
  {value: "John Erick Dowdle", label: "Dowdle, John Erick"},
  {value: "Michael Dowse", label: "Dowse, Michael"},
  {value: "Dennis Dugan", label: "Dugan, Dennis"},
  {value: "Duwayne Dunham", label: "Dunham, Duwayne"},
  {value: "Jesse Dylan", label: "Dylan, Jesse"},
  {value: "Clint Eastwood", label: "Eastwood, Clint"},
  {value: "Blake Edwards", label: "Edwards, Blake"},
  {value: "Breck Eisner", label: "Eisner, Breck"},
  {value: "David R. Ellis", label: "Ellis, David R."},
  {value: "Roland Emmerich", label: "Emmerich, Roland"},
  {value: "Nora Ephron", label: "Ephron, Nora"},
  {value: "David Mickey Evans", label: "Evans, David Mickey"},
  {value: "Gareth Evans", label: "Evans, Gareth"},
  {value: "Ben Falcone", label: "Falcone, Ben"},
  {value: "Bobby Farrelly", label: "Farrelly, Bobby"},
  {value: "Peter Farrelly", label: "Farrelly, Peter"},
  {value: "Jon Favreau", label: "Favreau, Jon"},
  {value: "Paul Feig", label: "Feig, Paul"},
  {value: "Federico Fellini", label: "Fellini, Federico"},
  {value: "Shana Feste", label: "Feste, Shana"},
  {value: "Andy Fickman", label: "Fickman, Andy"},
  {value: "David Fincher", label: "Fincher, David"},
  {value: "Mike Flanagan", label: "Flanagan, Mike"},
  {value: "Ruben Fleischer", label: "Fleischer, Ruben"},
  {value: "Andrew Fleming", label: "Fleming, Andrew"},
  {value: "Anne Fletcher", label: "Fletcher, Anne"},
  {value: "James Foley", label: "Foley, James"},
  {value: "Milos Forman", label: "Forman, Milos"},
  {value: "Marc Forster", label: "Forster, Marc"},
  {value: "Jonathan Frakes", label: "Frakes, Jonathan"},
  {value: "David Frankel", label: "Frankel, David"},
  {value: "John Frankenheimer", label: "Frankenheimer, John"},
  {value: "Stephen Frears", label: "Frears, Stephen"},
  {value: "Thor Freudenthal", label: "Freudenthal, Thor"},
  {value: "Jason Friedberg", label: "Friedberg, Jason"},
  {value: "William Friedkin", label: "Friedkin, William"},
  {value: "Antoine Fuqua", label: "Fuqua, Antoine"},
  {value: "Brad Furman", label: "Furman, Brad"},
  {value: "Rodrigo García", label: "García, Rodrigo"},
  {value: "Curt Geda", label: "Geda, Curt"},
  {value: "Clyde Geronimi", label: "Geronimi, Clyde"},
  {value: "Mel Gibson", label: "Gibson, Mel"},
  {value: "Lewis Gilbert", label: "Gilbert, Lewis"},
  {value: "Stuart Gillard", label: "Gillard, Stuart"},
  {value: "Craig Gillespie", label: "Gillespie, Craig"},
  {value: "Terry Gilliam", label: "Gilliam, Terry"},
  {value: "Dan Gilroy", label: "Gilroy, Dan"},
  {value: "Tony Gilroy", label: "Gilroy, Tony"},
  {value: "Paul Michael Glaser", label: "Glaser, Paul Michael"},
  {value: "John Glen", label: "Glen, John"},
  {value: "Will Gluck", label: "Gluck, Will"},
  {value: "Michel Gondry", label: "Gondry, Michel"},
  {value: "Josh Gordon", label: "Gordon, Josh"},
  {value: "Seth Gordon", label: "Gordon, Seth"},
  {value: "Raja Gosnell", label: "Gosnell, Raja"},
  {value: "F. Gary Gray", label: "Gray, F. Gary"},
  {value: "James Gray", label: "Gray, James"},
  {value: "David Gordon Green", label: "Green, David Gordon"},
  {value: "Luke Greenfield", label: "Greenfield, Luke"},
  {value: "Paul Greengrass", label: "Greengrass, Paul"},
  {value: "Kevin Greutert", label: "Greutert, Kevin"},
  {value: "Luca Guadagnino", label: "Guadagnino, Luca"},
  {value: "Christopher Guest", label: "Guest, Christopher"},
  {value: "James Gunn", label: "Gunn, James"},
  {value: "Taylor Hackford", label: "Hackford, Taylor"},
  {value: "Paul Haggis", label: "Haggis, Paul"},
  {value: "Brett Haley", label: "Haley, Brett"},
  {value: "Lasse Hallström", label: "Hallström, Lasse"},
  {value: "John Hamburg", label: "Hamburg, John"},
  {value: "Guy Hamilton", label: "Hamilton, Guy"},
  {value: "Sanaa Hamri", label: "Hamri, Sanaa"},
  {value: "John Lee Hancock", label: "Hancock, John Lee"},
  {value: "Michael Haneke", label: "Haneke, Michael"},
  {value: "Curtis Hanson", label: "Hanson, Curtis"},
  {value: "Catherine Hardwicke", label: "Hardwicke, Catherine"},
  {value: "Renny Harlin", label: "Harlin, Renny"},
  {value: "Julia Hart", label: "Hart, Julia"},
  {value: "Todd Haynes", label: "Haynes, Todd"},
  {value: "Jimmy Hayward", label: "Hayward, Jimmy"},
  {value: "Amy Heckerling", label: "Heckerling, Amy"},
  {value: "Peter Hedges", label: "Hedges, Peter"},
  {value: "Brian Helgeland", label: "Helgeland, Brian"},
  {value: "Marielle Heller", label: "Heller, Marielle"},
  {value: "Brian Henson", label: "Henson, Brian"},
  {value: "Stephen Herek", label: "Herek, Stephen"},
  {value: "Werner Herzog", label: "Herzog, Werner"},
  {value: "Jared Hess", label: "Hess, Jared"},
  {value: "Peter Hewitt", label: "Hewitt, Peter"},
  {value: "George Roy Hill", label: "Hill, George Roy"},
  {value: "Tim Hill", label: "Hill, Tim"},
  {value: "Walter Hill", label: "Hill, Walter"},
  {value: "Oliver Hirschbiegel", label: "Hirschbiegel, Oliver"},
  {value: "Alfred Hitchcock", label: "Hitchcock, Alfred"},
  {value: "Gregory Hoblit", label: "Hoblit, Gregory"},
  {value: "Paul Hoen", label: "Hoen, Paul"},
  {value: "Gavin Hood", label: "Hood, Gavin"},
  {value: "Tom Hooper", label: "Hooper, Tom"},
  {value: "Stephen Hopkins", label: "Hopkins, Stephen"},
  {value: "Ron Howard", label: "Howard, Ron"},
  {value: "Reginald Hudlin", label: "Hudlin, Reginald"},
  {value: "Allen Hughes", label: "Hughes, Allen"},
  {value: "John Hughes", label: "Hughes, John"},
  {value: "Mikael Håfström", label: "Håfström, Mikael"},
  {value: "Charles Stone III", label: "III, Charles Stone"},
  {value: "Robert Iscove", label: "Iscove, Robert"},
  {value: "Neal Israel", label: "Israel, Neal"},
  {value: "Alejandro G. Iñárritu", label: "Iñárritu, Alejandro G."},
  {value: "Peter Jackson", label: "Jackson, Peter"},
  {value: "Jim Jarmusch", label: "Jarmusch, Jim"},
  {value: "Norman Jewison", label: "Jewison, Norman"},
  {value: "Roland Joffé", label: "Joffé, Roland"},
  {value: "Kenneth Johnson", label: "Johnson, Kenneth"},
  {value: "Mark Steven Johnson", label: "Johnson, Mark Steven"},
  {value: "Rian Johnson", label: "Johnson, Rian"},
  {value: "Joe Johnston", label: "Johnston, Joe"},
  {value: "Duncan Jones", label: "Jones, Duncan"},
  {value: "Kirk Jones", label: "Jones, Kirk"},
  {value: "Terry Jones", label: "Jones, Terry"},
  {value: "Spike Jonze", label: "Jonze, Spike"},
  {value: "Bong Joon-ho", label: "Joon-ho, Bong"},
  {value: "Henry Joost", label: "Joost, Henry"},
  {value: "Neil Jordan", label: "Jordan, Neil"},
  {value: "Arthur Rankin Jr.", label: "Jr., Arthur Rankin"},
  {value: "George Tillman Jr.", label: "Jr., George Tillman"},
  {value: "Mike Judge", label: "Judge, Mike"},
  {value: "Gil Junger", label: "Junger, Gil"},
  {value: "Shekhar Kapur", label: "Kapur, Shekhar"},
  {value: "Jake Kasdan", label: "Kasdan, Jake"},
  {value: "Lawrence Kasdan", label: "Kasdan, Lawrence"},
  {value: "Charlie Kaufman", label: "Kaufman, Charlie"},
  {value: "Philip Kaufman", label: "Kaufman, Philip"},
  {value: "Richard Kelly", label: "Kelly, Richard"},
  {value: "Gil Kenan", label: "Kenan, Gil"},
  {value: "Erle C. Kenton", label: "Kenton, Erle C."},
  {value: "Takeshi Kitano", label: "Kitano, Takeshi"},
  {value: "Randal Kleiser", label: "Kleiser, Randal"},
  {value: "David Koepp", label: "Koepp, David"},
  {value: "Harmony Korine", label: "Korine, Harmony"},
  {value: "Baltasar Kormákur", label: "Kormákur, Baltasar"},
  {value: "Joseph Kosinski", label: "Kosinski, Joseph"},
  {value: "Ted Kotcheff", label: "Kotcheff, Ted"},
  {value: "Stanley Kubrick", label: "Kubrick, Stanley"},
  {value: "Roger Kumble", label: "Kumble, Roger"},
  {value: "Akira Kurosawa", label: "Kurosawa, Akira"},
  {value: "Karyn Kusama", label: "Kusama, Karyn"},
  {value: "Ken Kwapis", label: "Kwapis, Ken"},
  {value: "Richard LaGravenese", label: "LaGravenese, Richard"},
  {value: "John Landis", label: "Landis, John"},
  {value: "Christopher Landon", label: "Landon, Christopher"},
  {value: "Fritz Lang", label: "Lang, Fritz"},
  {value: "Yorgos Lanthimos", label: "Lanthimos, Yorgos"},
  {value: "John Lasseter", label: "Lasseter, John"},
  {value: "Francis Lawrence", label: "Lawrence, Francis"},
  {value: "Marc Lawrence", label: "Lawrence, Marc"},
  {value: "David Lean", label: "Lean, David"},
  {value: "Ang Lee", label: "Lee, Ang"},
  {value: "Malcolm D. Lee", label: "Lee, Malcolm D."},
  {value: "Spike Lee", label: "Lee, Spike"},
  {value: "Michael Lehmann", label: "Lehmann, Michael"},
  {value: "David Leitch", label: "Leitch, David"},
  {value: "Michael Lembeck", label: "Lembeck, Michael"},
  {value: "Kasi Lemmons", label: "Lemmons, Kasi"},
  {value: "Sergio Leone", label: "Leone, Sergio"},
  {value: "Louis Leterrier", label: "Leterrier, Louis"},
  {value: "Rob Letterman", label: "Letterman, Rob"},
  {value: "Brian Levant", label: "Levant, Brian"},
  {value: "Jonathan Levine", label: "Levine, Jonathan"},
  {value: "Barry Levinson", label: "Levinson, Barry"},
  {value: "Shawn Levy", label: "Levy, Shawn"},
  {value: "Jonathan Liebesman", label: "Liebesman, Jonathan"},
  {value: "Kevin Lima", label: "Lima, Kevin"},
  {value: "Doug Liman", label: "Liman, Doug"},
  {value: "Justin Lin", label: "Lin, Justin"},
  {value: "Richard Linklater", label: "Linklater, Richard"},
  {value: "Sam Liu", label: "Liu, Sam"},
  {value: "Phil Lord", label: "Lord, Phil"},
  {value: "David Lowery", label: "Lowery, David"},
  {value: "George Lucas", label: "Lucas, George"},
  {value: "Jon Lucas", label: "Lucas, Jon"},
  {value: "Baz Luhrmann", label: "Luhrmann, Baz"},
  {value: "Robert Luketic", label: "Luketic, Robert"},
  {value: "Sidney Lumet", label: "Lumet, Sidney"},
  {value: "Rod Lurie", label: "Lurie, Rod"},
  {value: "David Lynch", label: "Lynch, David"},
  {value: "Adrian Lyne", label: "Lyne, Adrian"},
  {value: "Jonathan Lynn", label: "Lynn, Jonathan"},
  {value: "Kevin Macdonald", label: "Macdonald, Kevin"},
  {value: "David Mackenzie", label: "Mackenzie, David"},
  {value: "John Madden", label: "Madden, John"},
  {value: "Sharon Maguire", label: "Maguire, Sharon"},
  {value: "Terrence Malick", label: "Malick, Terrence"},
  {value: "James Mangold", label: "Mangold, James"},
  {value: "Michael Mann", label: "Mann, Michael"},
  {value: "Garry Marshall", label: "Marshall, Garry"},
  {value: "Neil Marshall", label: "Marshall, Neil"},
  {value: "Penny Marshall", label: "Marshall, Penny"},
  {value: "Rob Marshall", label: "Marshall, Rob"},
  {value: "Les Mayfield", label: "Mayfield, Les"},
  {value: "Tom McCarthy", label: "McCarthy, Tom"},
  {value: "Martin McDonagh", label: "McDonagh, Martin"},
  {value: "McG", label: "McG, "},
  {value: "Paul McGuigan", label: "McGuigan, Paul"},
  {value: "Adam McKay", label: "McKay, Adam"},
  {value: "Sean McNamara", label: "McNamara, Sean"},
  {value: "Christopher McQuarrie", label: "McQuarrie, Christopher"},
  {value: "Steve McQueen", label: "McQueen, Steve"},
  {value: "James McTeigue", label: "McTeigue, James"},
  {value: "John McTiernan", label: "McTiernan, John"},
  {value: "Olivier Megaton", label: "Megaton, Olivier"},
  {value: "Fernando Meirelles", label: "Meirelles, Fernando"},
  {value: "Sam Mendes", label: "Mendes, Sam"},
  {value: "Nancy Meyers", label: "Meyers, Nancy"},
  {value: "Roger Michell", label: "Michell, Roger"},
  {value: "David Michôd", label: "Michôd, David"},
  {value: "Bennett Miller", label: "Miller, Bennett"},
  {value: "Christopher Miller", label: "Miller, Christopher"},
  {value: "Frank Miller", label: "Miller, Frank"},
  {value: "George Miller", label: "Miller, George"},
  {value: "Troy Miller", label: "Miller, Troy"},
  {value: "Steve Miner", label: "Miner, Steve"},
  {value: "Anthony Minghella", label: "Minghella, Anthony"},
  {value: "Rob Minkoff", label: "Minkoff, Rob"},
  {value: "Mike Mitchell", label: "Mitchell, Mike"},
  {value: "Gorō Miyazaki", label: "Miyazaki, Gorō"},
  {value: "Hayao Miyazaki", label: "Miyazaki, Hayao"},
  {value: "Lauren Montgomery", label: "Montgomery, Lauren"},
  {value: "Dito Montiel", label: "Montiel, Dito"},
  {value: "John Moore", label: "Moore, John"},
  {value: "Pierre Morel", label: "Morel, Pierre"},
  {value: "Jonathan Mostow", label: "Mostow, Jonathan"},
  {value: "Greg Mottola", label: "Mottola, Greg"},
  {value: "Gabriele Muccino", label: "Muccino, Gabriele"},
  {value: "Russell Mulcahy", label: "Mulcahy, Russell"},
  {value: "Andy Muschietti", label: "Muschietti, Andy"},
  {value: "John Musker", label: "Musker, John"},
  {value: "Mira Nair", label: "Nair, Mira"},
  {value: "Vincenzo Natali", label: "Natali, Vincenzo"},
  {value: "Mark Neveldine", label: "Neveldine, Mark"},
  {value: "Mike Newell", label: "Newell, Mike"},
  {value: "Andrew Niccol", label: "Niccol, Andrew"},
  {value: "Jeff Nichols", label: "Nichols, Jeff"},
  {value: "Mike Nichols", label: "Nichols, Mike"},
  {value: "Leonard Nimoy", label: "Nimoy, Leonard"},
  {value: "Marcus Nispel", label: "Nispel, Marcus"},
  {value: "Christopher Nolan", label: "Nolan, Christopher"},
  {value: "Phillip Noyce", label: "Noyce, Phillip"},
  {value: "Gaspar Noé", label: "Noé, Gaspar"},
  {value: "Declan O'Brien", label: "O'Brien, Declan"},
  {value: "Gavin O'Connor", label: "O'Connor, Gavin"},
  {value: "Bob Odenkirk", label: "Odenkirk, Bob"},
  {value: "Steve Oedekerk", label: "Oedekerk, Steve"},
  {value: "Jay Oliva", label: "Oliva, Jay"},
  {value: "Kenny Ortega", label: "Ortega, Kenny"},
  {value: "Frank Oz", label: "Oz, Frank"},
  {value: "José Padilha", label: "Padilha, José"},
  {value: "Alan J. Pakula", label: "Pakula, Alan J."},
  {value: "Brian De Palma", label: "Palma, Brian De"},
  {value: "Dean Parisot", label: "Parisot, Dean"},
  {value: "Trey Parker", label: "Parker, Trey"},
  {value: "John Pasquin", label: "Pasquin, John"},
  {value: "Don Michael Paul", label: "Paul, Don Michael"},
  {value: "Pawel Pawlikowski", label: "Pawlikowski, Pawel"},
  {value: "Alexander Payne", label: "Payne, Alexander"},
  {value: "Jesse Peretz", label: "Peretz, Jesse"},
  {value: "Tyler Perry", label: "Perry, Tyler"},
  {value: "Wolfgang Petersen", label: "Petersen, Wolfgang"},
  {value: "Daniel Petrie", label: "Petrie, Daniel"},
  {value: "Donald Petrie", label: "Petrie, Donald"},
  {value: "Brad Peyton", label: "Peyton, Brad"},
  {value: "Todd Phillips", label: "Phillips, Todd"},
  {value: "Steve Pink", label: "Pink, Steve"},
  {value: "Roman Polanski", label: "Polanski, Roman"},
  {value: "Sydney Pollack", label: "Pollack, Sydney"},
  {value: "James Ponsoldt", label: "Ponsoldt, James"},
  {value: "Ted Post", label: "Post, Ted"},
  {value: "Gina Prince-Bythewood", label: "Prince-Bythewood, Gina"},
  {value: "Alex Proyas", label: "Proyas, Alex"},
  {value: "Sam Raimi", label: "Raimi, Sam"},
  {value: "Harold Ramis", label: "Ramis, Harold"},
  {value: "Steve Rash", label: "Rash, Steve"},
  {value: "Brett Ratner", label: "Ratner, Brett"},
  {value: "Robert Redford", label: "Redford, Robert"},
  {value: "Peyton Reed", label: "Reed, Peyton"},
  {value: "Dee Rees", label: "Rees, Dee"},
  {value: "Matt Reeves", label: "Reeves, Matt"},
  {value: "Nicolas Winding Refn", label: "Refn, Nicolas Winding"},
  {value: "Rob Reiner", label: "Reiner, Rob"},
  {value: "Wolfgang Reitherman", label: "Reitherman, Wolfgang"},
  {value: "Ivan Reitman", label: "Reitman, Ivan"},
  {value: "Jason Reitman", label: "Reitman, Jason"},
  {value: "Chris Renaud", label: "Renaud, Chris"},
  {value: "John Requa", label: "Requa, John"},
  {value: "Kevin Reynolds", label: "Reynolds, Kevin"},
  {value: "Guy Ritchie", label: "Ritchie, Guy"},
  {value: "Michael Ritchie", label: "Ritchie, Michael"},
  {value: "Jay Roach", label: "Roach, Jay"},
  {value: "Brian Robbins", label: "Robbins, Brian"},
  {value: "Johannes Roberts", label: "Roberts, Johannes"},
  {value: "Phil Alden Robinson", label: "Robinson, Phil Alden"},
  {value: "Todd Robinson", label: "Robinson, Todd"},
  {value: "Chris Rock", label: "Rock, Chris"},
  {value: "Robert Rodriguez", label: "Rodriguez, Robert"},
  {value: "George A. Romero", label: "Romero, George A."},
  {value: "Gary Ross", label: "Ross, Gary"},
  {value: "Eli Roth", label: "Roth, Eli"},
  {value: "Joe Roth", label: "Roth, Joe"},
  {value: "Chuck Russell", label: "Russell, Chuck"},
  {value: "David O. Russell", label: "Russell, David O."},
  {value: "Jay Russell", label: "Russell, Jay"},
  {value: "Anthony Russo", label: "Russo, Anthony"},
  {value: "Joe Russo", label: "Russo, Joe"},
  {value: "Joachim Rønning", label: "Rønning, Joachim"},
  {value: "Benny Safdie", label: "Safdie, Benny"},
  {value: "Josh Safdie", label: "Safdie, Josh"},
  {value: "Carlos Saldanha", label: "Saldanha, Carlos"},
  {value: "David F. Sandberg", label: "Sandberg, David F."},
  {value: "Chris Sanders", label: "Sanders, Chris"},
  {value: "Gus Van Sant", label: "Sant, Gus Van"},
  {value: "Jeremy Saulnier", label: "Saulnier, Jeremy"},
  {value: "Akiva Schaffer", label: "Schaffer, Akiva"},
  {value: "Paul Schrader", label: "Schrader, Paul"},
  {value: "John Schultz", label: "Schultz, John"},
  {value: "Joel Schumacher", label: "Schumacher, Joel"},
  {value: "Robert Schwentke", label: "Schwentke, Robert"},
  {value: "Martin Scorsese", label: "Scorsese, Martin"},
  {value: "Ridley Scott", label: "Scott, Ridley"},
  {value: "Tony Scott", label: "Scott, Tony"},
  {value: "Peter Segal", label: "Segal, Peter"},
  {value: "Aaron Seltzer", label: "Seltzer, Aaron"},
  {value: "Dominic Sena", label: "Sena, Dominic"},
  {value: "Tom Shadyac", label: "Shadyac, Tom"},
  {value: "Adam Shankman", label: "Shankman, Adam"},
  {value: "John Patrick Shanley", label: "Shanley, John Patrick"},
  {value: "Lynn Shelton", label: "Shelton, Lynn"},
  {value: "Ron Shelton", label: "Shelton, Ron"},
  {value: "Jim Sheridan", label: "Sheridan, Jim"},
  {value: "Takashi Shimizu", label: "Shimizu, Takashi"},
  {value: "Makoto Shinkai", label: "Shinkai, Makoto"},
  {value: "M. Night Shyamalan", label: "Shyamalan, M. Night"},
  {value: "Don Siegel", label: "Siegel, Don"},
  {value: "Brad Silberling", label: "Silberling, Brad"},
  {value: "Bryan Singer", label: "Singer, Bryan"},
  {value: "Tarsem Singh", label: "Singh, Tarsem"},
  {value: "John Singleton", label: "Singleton, John"},
  {value: "Charles Martin Smith", label: "Smith, Charles Martin"},
  {value: "Kevin Smith", label: "Smith, Kevin"},
  {value: "Zack Snyder", label: "Snyder, Zack"},
  {value: "Steven Soderbergh", label: "Soderbergh, Steven"},
  {value: "Stephen Sommers", label: "Sommers, Stephen"},
  {value: "Barry Sonnenfeld", label: "Sonnenfeld, Barry"},
  {value: "Penelope Spheeris", label: "Spheeris, Penelope"},
  {value: "Steven Spielberg", label: "Spielberg, Steven"},
  {value: "Michael Spierig", label: "Spierig, Michael"},
  {value: "Peter Spierig", label: "Spierig, Peter"},
  {value: "Chad Stahleski", label: "Stahleski, Chad"},
  {value: "Sylvester Stallone", label: "Stallone, Sylvester"},
  {value: "Andrew Stanton", label: "Stanton, Andrew"},
  {value: "Burr Steers", label: "Steers, Burr"},
  {value: "Scott Stewart", label: "Stewart, Scott"},
  {value: "Ben Stiller", label: "Stiller, Ben"},
  {value: "Nicholas Stoller", label: "Stoller, Nicholas"},
  {value: "Oliver Stone", label: "Stone, Oliver"},
  {value: "Tim Story", label: "Story, Tim"},
  {value: "Todd Strauss-Schulson", label: "Strauss-Schulson, Todd"},
  {value: "Joe Swanberg", label: "Swanberg, Joe"},
  {value: "Isao Takahata", label: "Takahata, Isao"},
  {value: "David E. Talbert", label: "Talbert, David E."},
  {value: "Lee Tamahori", label: "Tamahori, Lee"},
  {value: "Quentin Tarantino", label: "Tarantino, Quentin"},
  {value: "Genndy Tartakovsky", label: "Tartakovsky, Genndy"},
  {value: "Deon Taylor", label: "Taylor, Deon"},
  {value: "Tate Taylor", label: "Taylor, Tate"},
  {value: "Sam Taylor-Johnson", label: "Taylor-Johnson, Sam"},
  {value: "Julie Taymor", label: "Taymor, Julie"},
  {value: "Andy Tennant", label: "Tennant, Andy"},
  {value: "Betty Thomas", label: "Thomas, Betty"},
  {value: "Rawson Marshall Thurber", label: "Thurber, Rawson Marshall"},
  {value: "Michael Tiddes", label: "Tiddes, Michael"},
  {value: "Guillermo del Toro", label: "Toro, Guillermo del"},
  {value: "Josh Trank", label: "Trank, Josh"},
  {value: "Jeff Tremaine", label: "Tremaine, Jeff"},
  {value: "Colin Trevorrow", label: "Trevorrow, Colin"},
  {value: "Lars von Trier", label: "Trier, Lars von"},
  {value: "Gary Trousdale", label: "Trousdale, Gary"},
  {value: "Jon Turteltaub", label: "Turteltaub, Jon"},
  {value: "David Twohy", label: "Twohy, David"},
  {value: "Tom Tykwer", label: "Tykwer, Tom"},
  {value: "Morten Tyldum", label: "Tyldum, Morten"},
  {value: "Ron Underwood", label: "Underwood, Ron"},
  {value: "Jean-Marc Vallée", label: "Vallée, Jean-Marc"},
  {value: "Tom Vaughan", label: "Vaughan, Tom"},
  {value: "Matthew Vaughn", label: "Vaughn, Matthew"},
  {value: "Gore Verbinski", label: "Verbinski, Gore"},
  {value: "Paul Verhoeven", label: "Verhoeven, Paul"},
  {value: "Denis Villeneuve", label: "Villeneuve, Denis"},
  {value: "Thomas Vinterberg", label: "Vinterberg, Thomas"},
  {value: "Lana Wachowski", label: "Wachowski, Lana"},
  {value: "Lilly Wachowski", label: "Wachowski, Lilly"},
  {value: "Jeff Wadlow", label: "Wadlow, Jeff"},
  {value: "David Wain", label: "Wain, David"},
  {value: "Taika Waititi", label: "Waititi, Taika"},
  {value: "Randall Wallace", label: "Wallace, Randall"},
  {value: "James Wan", label: "Wan, James"},
  {value: "David S. Ward", label: "Ward, David S."},
  {value: "Mark Waters", label: "Waters, Mark"},
  {value: "Jon Watts", label: "Watts, Jon"},
  {value: "Ric Roman Waugh", label: "Waugh, Ric Roman"},
  {value: "Keenen Ivory Wayans", label: "Wayans, Keenen Ivory"},
  {value: "Marc Webb", label: "Webb, Marc"},
  {value: "Chris Wedge", label: "Wedge, Chris"},
  {value: "Peter Weir", label: "Weir, Peter"},
  {value: "Sam Weisman", label: "Weisman, Sam"},
  {value: "Chris Weitz", label: "Weitz, Chris"},
  {value: "Paul Weitz", label: "Weitz, Paul"},
  {value: "John Wells", label: "Wells, John"},
  {value: "Simon Wells", label: "Wells, Simon"},
  {value: "Simon West", label: "West, Simon"},
  {value: "James Whale", label: "Whale, James"},
  {value: "Leigh Whannell", label: "Whannell, Leigh"},
  {value: "Ben Wheatley", label: "Wheatley, Ben"},
  {value: "Joss Whedon", label: "Whedon, Joss"},
  {value: "Sylvain White", label: "White, Sylvain"},
  {value: "John Whitesell", label: "Whitesell, John"},
  {value: "Billy Wilder", label: "Wilder, Billy"},
  {value: "Simon Wincer", label: "Wincer, Simon"},
  {value: "Adam Wingard", label: "Wingard, Adam"},
  {value: "Gary Winick", label: "Winick, Gary"},
  {value: "Michael Winterbottom", label: "Winterbottom, Michael"},
  {value: "Robert Wise", label: "Wise, Robert"},
  {value: "Len Wiseman", label: "Wiseman, Len"},
  {value: "James Wong", label: "Wong, James"},
  {value: "John Woo", label: "Woo, John"},
  {value: "Edgar Wright", label: "Wright, Edgar"},
  {value: "Joe Wright", label: "Wright, Joe"},
  {value: "Boaz Yakin", label: "Yakin, Boaz"},
  {value: "David Yates", label: "Yates, David"},
  {value: "Terence Young", label: "Young, Terence"},
  {value: "Ronny Yu", label: "Yu, Ronny"},
  {value: "Robert Zemeckis", label: "Zemeckis, Robert"},
  {value: "Rob Zombie", label: "Zombie, Rob"},
  {value: "David Zucker", label: "Zucker, David"},
  {value: "Jerry Zucker", label: "Zucker, Jerry"},
  {value: "Harald Zwart", label: "Zwart, Harald"},
  {value: "Edward Zwick", label: "Zwick, Edward"},
]

export const genreOptions: DropdownOption[] = [
  {value: "Action", label: "Action"},
  {value: "Adventure", label: "Adventure"},
  {value: "Animation", label: "Animation"},
  {value: "Anime", label: "Anime"},
  {value: "Comedy", label: "Comedy"},
  {value: "Comic", label: "Comic"},
  {value: "Crime", label: "Crime"},
  {value: "Disaster", label: "Disaster"},
  {value: "Drama", label: "Drama"},
  {value: "Dramedy", label: "Dramedy"},
  {value: "Fantasy", label: "Fantasy"},
  {value: "Horror", label: "Horror"},
  {value: "Musical", label: "Musical"},
  {value: "Mystery", label: "Mystery"},
  {value: "RomCom", label: "RomCom"},
  {value: "Romance", label: "Romance"},
  {value: "Sci-Fi", label: "Sci-Fi"},
  {value: "Sports", label: "Sports"},
  {value: "Thriller", label: "Thriller"},
  {value: "Western", label: "Western"},
]

export const subGenreOptions: DropdownOption[] = [
  {value: "Action Adventure", label: "Action Adventure"},
  {value: "Action Comedy", label: "Action Comedy"},
  {value: "Action Thriller", label: "Action Thriller"},
  {value: "Adult Animation", label: "Adult Animation"},
  {value: "Alien Invasion", label: "Alien Invasion"},
  {value: "Assassins/Hitmen & Gunslingers", label: "Assassins/Hitmen & Gunslingers"},
  {value: "BioPic & True Story", label: "BioPic & True Story"},
  {value: "Biopic & True Story", label: "Biopic & True Story"},
  {value: "Buddies & Screwballs", label: "Buddies & Screwballs"},
  {value: "Comedy-of-Age", label: "Comedy-of-Age"},
  {value: "Coming-of-Age", label: "Coming-of-Age"},
  {value: "Cooking", label: "Cooking"},
  {value: "Courtroom & Legal", label: "Courtroom & Legal"},
  {value: "Crime Thriller", label: "Crime Thriller"},
  {value: "Dance & Music", label: "Dance & Music"},
  {value: "Dark Comedy", label: "Dark Comedy"},
  {value: "Demons & Possession", label: "Demons & Possession"},
  {value: "Dinosaurs", label: "Dinosaurs"},
  {value: "Disaster & Apocalypse", label: "Disaster & Apocalypse"},
  {value: "Dystopian", label: "Dystopian"},
  {value: "Erotic Thriller", label: "Erotic Thriller"},
  {value: "Family Comedy", label: "Family Comedy"},
  {value: "Family Dynamics", label: "Family Dynamics"},
  {value: "Fantasy Comedy", label: "Fantasy Comedy"},
  {value: "Fast Cars & Getaways", label: "Fast Cars & Getaways"},
  {value: "Gangster & Mafia/Mob", label: "Gangster & Mafia/Mob"},
  {value: "Gangster & Mob/Mafia", label: "Gangster & Mob/Mafia"},
  {value: "Haunted & Paranormal", label: "Haunted & Paranormal"},
  {value: "Heist", label: "Heist"},
  {value: "Hidden Camera", label: "Hidden Camera"},
  {value: "Hitman & Assassins", label: "Hitman & Assassins"},
  {value: "Hitmen & Assassins", label: "Hitmen & Assassins"},
  {value: "Horror Comedy", label: "Horror Comedy"},
  {value: "Horror Thriller", label: "Horror Thriller"},
  {value: "Kids & Family", label: "Kids & Family"},
  {value: "LGBTQ+", label: "LGBTQ+"},
  {value: "Mall Cop", label: "Mall Cop"},
  {value: "Mecha & Gundam", label: "Mecha & Gundam"},
  {value: "Melodrama", label: "Melodrama"},
  {value: "Monsters & Creatures", label: "Monsters & Creatures"},
  {value: "Musical", label: "Musical"},
  {value: "Mystery & Suspense", label: "Mystery & Suspense"},
  {value: "Neo-Western", label: "Neo-Western"},
  {value: "Parody & Satire/Spoof", label: "Parody & Satire/Spoof"},
  {value: "Parody & Staire/Spoof", label: "Parody & Staire/Spoof"},
  {value: "Police & Detectives", label: "Police & Detectives"},
  {value: "Political", label: "Political"},
  {value: "Political Thriller", label: "Political Thriller"},
  {value: "Psychological Horror", label: "Psychological Horror"},
  {value: "Psychological Thriller", label: "Psychological Thriller"},
  {value: "Raunchy & Sex Humor", label: "Raunchy & Sex Humor"},
  {value: "Religion", label: "Religion"},
  {value: "Religious", label: "Religious"},
  {value: "Road/Roadtrip & Travel", label: "Road/Roadtrip & Travel"},
  {value: "Romantic Drama", label: "Romantic Drama"},
  {value: "Sci-Fi Thriller", label: "Sci-Fi Thriller"},
  {value: "Secret Agent & Espionage", label: "Secret Agent & Espionage"},
  {value: "Secret Agents & Espionage", label: "Secret Agents & Espionage"},
  {value: "Silent Film", label: "Silent Film"},
  {value: "Silent Movie", label: "Silent Movie"},
  {value: "Slasher & Shock/Gore", label: "Slasher & Shock/Gore"},
  {value: "Social & Political Commentary", label: "Social & Political Commentary"},
  {value: "Space", label: "Space"},
  {value: "Spaghetti Western", label: "Spaghetti Western"},
  {value: "Stand-Up", label: "Stand-Up"},
  {value: "Stoner Flick", label: "Stoner Flick"},
  {value: "Sword & Sandal", label: "Sword & Sandal"},
  {value: "Teen Comedy", label: "Teen Comedy"},
  {value: "Teen Scream", label: "Teen Scream"},
  {value: "Teen Screen", label: "Teen Screen"},
  {value: "Time Travel", label: "Time Travel"},
  {value: "Video Game", label: "Video Game"},
  {value: "War", label: "War"},
  {value: "Witches & Wizards", label: "Witches & Wizards"},
  {value: "Young Adult", label: "Young Adult"},
  {value: "Zombie", label: "Zombie"},
]

const studiocompanyFeatured: DropdownOption[] = [
  { value: '20th Century Studios', label: '20th Century Studios' },
  { value: 'A24', label: 'A24' },
  { value: 'Amazon Studios', label: 'Amazon Studios' },
  { value: 'Blumhouse', label: 'Blumhouse' },
  { value: 'Columbia Pictures', label: 'Columbia Pictures' },
  { value: 'DC', label: 'DC' },
  { value: 'Dimension Films', label: 'Dimension Films' },
  { value: 'Disney', label: 'Disney' },
  { value: 'DreamWorks Pictures', label: 'DreamWorks Pictures' },
  { value: 'Happy Madison', label: 'Happy Madison' },
  { value: 'HBO', label: 'HBO' },
  { value: 'Lucasfilm', label: 'Lucasfilm' },
  { value: 'Marvel', label: 'Marvel' },
  { value: 'MGM Studios', label: 'MGM Studios' },
  { value: 'NEON', label: 'NEON' },
  { value: 'Netflix', label: 'Netflix' },
  { value: 'Nickelodeon', label: 'Nickelodeon' },
  { value: 'Paramount Pictures', label: 'Paramount Pictures' },
  { value: 'Searchlight Pictures', label: 'Searchlight Pictures' },
  { value: 'Sony Pictures', label: 'Sony Pictures' },
  { value: 'Studio Ghibli', label: 'Studio Ghibli' },
  { value: 'Universal Pictures', label: 'Universal Pictures' },
  { value: 'Warner Bros.', label: 'Warner Bros.' },
]

const studiocompanyOther: DropdownOption[] = [
  {value: "40 Acres and a Mule Filmworks", label: "40 Acres and a Mule Filmworks"},
  {value: "A-Pix Entertainment", label: "A-Pix Entertainment"},
  {value: "AGBO", label: "AGBO"},
  {value: "AMC Networks", label: "AMC Networks"},
  {value: "ATO Pictures", label: "ATO Pictures"},
  {value: "Aardman Animation", label: "Aardman Animation"},
  {value: "Absurda Inc.", label: "Absurda Inc."},
  {value: "Acme Rocket Fuel", label: "Acme Rocket Fuel"},
  {value: "Adult Swim", label: "Adult Swim"},
  {value: "Alliance Films", label: "Alliance Films"},
  {value: "Allied Artists Pictures", label: "Allied Artists Pictures"},
  {value: "Amazing Incorporated", label: "Amazing Incorporated"},
  {value: "Amblin", label: "Amblin"},
  {value: "American International Pictures", label: "American International Pictures"},
  {value: "Amplify", label: "Amplify"},
  {value: "Anchor Bay Entertainment", label: "Anchor Bay Entertainment"},
  {value: "Annapurna Pictures", label: "Annapurna Pictures"},
  {value: "Apatow Productions", label: "Apatow Productions"},
  {value: "Apparition", label: "Apparition"},
  {value: "Apple TV+", label: "Apple TV+"},
  {value: "Aries Films", label: "Aries Films"},
  {value: "Arrival Pictures", label: "Arrival Pictures"},
  {value: "Arte France Cinema", label: "Arte France Cinema"},
  {value: "Artificial Eye", label: "Artificial Eye"},
  {value: "Artisan Entertainment", label: "Artisan Entertainment"},
  {value: "Astor Pictures", label: "Astor Pictures"},
  {value: "Atlas Entertainment", label: "Atlas Entertainment"},
  {value: "Avalanche Animation", label: "Avalanche Animation"},
  {value: "Avenue Entertainment", label: "Avenue Entertainment"},
  {value: "Aviron Pictures", label: "Aviron Pictures"},
  {value: "B.O.M. Film Productions Co.", label: "B.O.M. Film Productions Co."},
  {value: "BBC Films", label: "BBC Films"},
  {value: "BRON", label: "BRON"},
  {value: "Bandai Entertainment", label: "Bandai Entertainment"},
  {value: "Beijing New Picture Film", label: "Beijing New Picture Film"},
  {value: "Bitter Films", label: "Bitter Films"},
  {value: "Black Bear Pictures", label: "Black Bear Pictures"},
  {value: "Black Diamond Pictures", label: "Black Diamond Pictures"},
  {value: "Bleecker Street", label: "Bleecker Street"},
  {value: "Blinder Films", label: "Blinder Films"},
  {value: "Blue Sky Animation", label: "Blue Sky Animation"},
  {value: "Bluefields Entertainment", label: "Bluefields Entertainment"},
  {value: "Boo Productions", label: "Boo Productions"},
  {value: "Bounty Films", label: "Bounty Films"},
  {value: "Brainstorm media", label: "Brainstorm media"},
  {value: "British Lion Films", label: "British Lion Films"},
  {value: "Broad Green Pictures", label: "Broad Green Pictures"},
  {value: "Bryanston Pictures", label: "Bryanston Pictures"},
  {value: "Buena Vista International", label: "Buena Vista International"},
  {value: "Buena Vista Pictures", label: "Buena Vista Pictures"},
  {value: "CBS Films", label: "CBS Films"},
  {value: "CGV Arthouse", label: "CGV Arthouse"},
  {value: "CJ Entertainment", label: "CJ Entertainment"},
  {value: "Canal+", label: "Canal+"},
  {value: "Cannon Films", label: "Cannon Films"},
  {value: "Cartoon Saloon", label: "Cartoon Saloon"},
  {value: "Central Motion Pictures", label: "Central Motion Pictures"},
  {value: "Chernin", label: "Chernin"},
  {value: "Chicago Releasing", label: "Chicago Releasing"},
  {value: "China Film Group", label: "China Film Group"},
  {value: "China Star Entertainment Group", label: "China Star Entertainment Group"},
  {value: "Cinedigm", label: "Cinedigm"},
  {value: "Cinema 5", label: "Cinema 5"},
  {value: "Cineplex-Odeon Films", label: "Cineplex-Odeon Films"},
  {value: "Cineriz", label: "Cineriz"},
  {value: "CoMix Wave Films", label: "CoMix Wave Films"},
  {value: "CollegeHumor", label: "CollegeHumor"},
  {value: "Compass International Pictures", label: "Compass International Pictures"},
  {value: "Constantin Film", label: "Constantin Film"},
  {value: "Continental Distributing", label: "Continental Distributing"},
  {value: "Convoy Entertainment", label: "Convoy Entertainment"},
  {value: "Crane Movie Company", label: "Crane Movie Company"},
  {value: "Crest Animation", label: "Crest Animation"},
  {value: "Crook Brothers Films", label: "Crook Brothers Films"},
  {value: "Crossbow Productions", label: "Crossbow Productions"},
  {value: "DUST", label: "DUST"},
  {value: "Dark Horse", label: "Dark Horse"},
  {value: "Dark Sky Films", label: "Dark Sky Films"},
  {value: "Destination Films", label: "Destination Films"},
  {value: "Det Danske Filminstitut", label: "Det Danske Filminstitut"},
  {value: "Drafthouse Films", label: "Drafthouse Films"},
  {value: "DreamWorks Animation", label: "DreamWorks Animation"},
  {value: "Duplass Brothers Productions", label: "Duplass Brothers Productions"},
  {value: "ESPN", label: "ESPN"},
  {value: "ESX Entertainment", label: "ESX Entertainment"},
  {value: "Electric Entertainment", label: "Electric Entertainment"},
  {value: "Element Pictures", label: "Element Pictures"},
  {value: "Embassy Pictures", label: "Embassy Pictures"},
  {value: "Endgame Entertainment", label: "Endgame Entertainment"},
  {value: "Entertainment One", label: "Entertainment One"},
  {value: "Entertainment Studios", label: "Entertainment Studios"},
  {value: "Epic Pictures", label: "Epic Pictures"},
  {value: "EuropaCorp", label: "EuropaCorp"},
  {value: "Fantastic Films International", label: "Fantastic Films International"},
  {value: "Fbi Films", label: "Fbi Films"},
  {value: "Film4", label: "Film4"},
  {value: "FilmDistrict", label: "FilmDistrict"},
  {value: "FilmRise", label: "FilmRise"},
  {value: "Filmel", label: "Filmel"},
  {value: "Filmways Pictures", label: "Filmways Pictures"},
  {value: "Fine Line Features", label: "Fine Line Features"},
  {value: "First Independent Pictures", label: "First Independent Pictures"},
  {value: "First Look Studios", label: "First Look Studios"},
  {value: "Focus Features", label: "Focus Features"},
  {value: "Focus World", label: "Focus World"},
  {value: "Franchise Pictures", label: "Franchise Pictures"},
  {value: "Freestyle Releasing", label: "Freestyle Releasing"},
  {value: "Freestyling Releasing", label: "Freestyling Releasing"},
  {value: "Full Circle Releasing", label: "Full Circle Releasing"},
  {value: "Fundamental Films", label: "Fundamental Films"},
  {value: "GAGA Pictures", label: "GAGA Pictures"},
  {value: "Galaxy Releasing", label: "Galaxy Releasing"},
  {value: "Gamechanger Films", label: "Gamechanger Films"},
  {value: "Gary Sanchez", label: "Gary Sanchez"},
  {value: "Gaumont Film Company", label: "Gaumont Film Company"},
  {value: "Global Road Entertainment", label: "Global Road Entertainment"},
  {value: "Gloria Sanchez", label: "Gloria Sanchez"},
  {value: "GoDigital", label: "GoDigital"},
  {value: "Golden Harvest", label: "Golden Harvest"},
  {value: "Golden Princess Film Production", label: "Golden Princess Film Production"},
  {value: "Goldrush Entertainment", label: "Goldrush Entertainment"},
  {value: "Good Deed Entertainment", label: "Good Deed Entertainment"},
  {value: "Gramercy Pictures", label: "Gramercy Pictures"},
  {value: "Granada Television", label: "Granada Television"},
  {value: "Gravitas Ventures", label: "Gravitas Ventures"},
  {value: "Gunpowder & Sky", label: "Gunpowder & Sky"},
  {value: "Hallmark", label: "Hallmark"},
  {value: "Hayhoe Studios", label: "Hayhoe Studios"},
  {value: "Helsinki-filmi", label: "Helsinki-filmi"},
  {value: "High Top Releasing", label: "High Top Releasing"},
  {value: "Horror Collective", label: "Horror Collective"},
  {value: "Huhu Animation", label: "Huhu Animation"},
  {value: "Hulu", label: "Hulu"},
  {value: "Hyperion Pictures", label: "Hyperion Pictures"},
  {value: "I.R.S. Releasing", label: "I.R.S. Releasing"},
  {value: "IFC Films", label: "IFC Films"},
  {value: "Icon Film Distribution", label: "Icon Film Distribution"},
  {value: "Illumination", label: "Illumination"},
  {value: "Imagine Entertainment", label: "Imagine Entertainment"},
  {value: "Inc.", label: "Inc."},
  {value: "Indomina Releasing", label: "Indomina Releasing"},
  {value: "Ingenious Media", label: "Ingenious Media"},
  {value: "Invincible Pictures", label: "Invincible Pictures"},
  {value: "Irish Film Board", label: "Irish Film Board"},
  {value: "Jet Tone Production", label: "Jet Tone Production"},
  {value: "Jhumka Films", label: "Jhumka Films"},
  {value: "Jinga Films", label: "Jinga Films"},
  {value: "Juno Films", label: "Juno Films"},
  {value: "Kadokawa Herald Pictures", label: "Kadokawa Herald Pictures"},
  {value: "Karbo Vantas Entertainment", label: "Karbo Vantas Entertainment"},
  {value: "Keystone Pictures", label: "Keystone Pictures"},
  {value: "Kick the Machine", label: "Kick the Machine"},
  {value: "LD Entertainment", label: "LD Entertainment"},
  {value: "Laika Animation", label: "Laika Animation"},
  {value: "Lakeshore Entertainment", label: "Lakeshore Entertainment"},
  {value: "Lantern Entertainment", label: "Lantern Entertainment"},
  {value: "Lee Mendelson Films", label: "Lee Mendelson Films"},
  {value: "Legacy Releasing", label: "Legacy Releasing"},
  {value: "Legendary Pictures", label: "Legendary Pictures"},
  {value: "Libra Films", label: "Libra Films"},
  {value: "Lionsgate", label: "Lionsgate"},
  {value: "MPI Media Group", label: "MPI Media Group"},
  {value: "MTV Films", label: "MTV Films"},
  {value: "MUBI", label: "MUBI"},
  {value: "Madhouse", label: "Madhouse"},
  {value: "Madman Films", label: "Madman Films"},
  {value: "Magellan Pictures", label: "Magellan Pictures"},
  {value: "Magnet Releasing", label: "Magnet Releasing"},
  {value: "Magnolia Pictures", label: "Magnolia Pictures"},
  {value: "Mandarin Films", label: "Mandarin Films"},
  {value: "Manga Entertainment", label: "Manga Entertainment"},
  {value: "Marv Films", label: "Marv Films"},
  {value: "Maven Screen Media", label: "Maven Screen Media"},
  {value: "Memento Films", label: "Memento Films"},
  {value: "Millenium Films", label: "Millenium Films"},
  {value: "Millennium Films", label: "Millennium Films"},
  {value: "Miramax", label: "Miramax"},
  {value: "Miramax Films", label: "Miramax Films"},
  {value: "Momentum Pictures", label: "Momentum Pictures"},
  {value: "Mosfilm", label: "Mosfilm"},
  {value: "MoviePass Films", label: "MoviePass Films"},
  {value: "MoviePass Ventures", label: "MoviePass Ventures"},
  {value: "Music Box Films", label: "Music Box Films"},
  {value: "NDM", label: "NDM"},
  {value: "NeoClassics Films", label: "NeoClassics Films"},
  {value: "Nero-Fim A.G.", label: "Nero-Fim A.G."},
  {value: "Netflix Original", label: "Netflix Original"},
  {value: "New Artist Pictures", label: "New Artist Pictures"},
  {value: "New Line Cinema", label: "New Line Cinema"},
  {value: "New World Pictures", label: "New World Pictures"},
  {value: "Newmarket Capital Group", label: "Newmarket Capital Group"},
  {value: "Newmarket Film Group", label: "Newmarket Film Group"},
  {value: "Next Entertainment World", label: "Next Entertainment World"},
  {value: "Nickelodeon Movies", label: "Nickelodeon Movies"},
  {value: "Nimbus Film", label: "Nimbus Film"},
  {value: "Nordisk Film", label: "Nordisk Film"},
  {value: "October Films", label: "October Films"},
  {value: "Open Road Films", label: "Open Road Films"},
  {value: "Optimum Releasing", label: "Optimum Releasing"},
  {value: "Orchard", label: "Orchard"},
  {value: "Orion Pictures", label: "Orion Pictures"},
  {value: "Oro Films", label: "Oro Films"},
  {value: "Oscilloscope Laboratories", label: "Oscilloscope Laboratories"},
  {value: "Oscilloscope Pictures", label: "Oscilloscope Pictures"},
  {value: "Overture Films", label: "Overture Films"},
  {value: "Paladin", label: "Paladin"},
  {value: "Pantelion Films", label: "Pantelion Films"},
  {value: "Paper Kite Productions", label: "Paper Kite Productions"},
  {value: "Pathé Distribution", label: "Pathé Distribution"},
  {value: "Peace Arch Entertainment", label: "Peace Arch Entertainment"},
  {value: "Picturehouse Entertainment", label: "Picturehouse Entertainment"},
  {value: "Piki Films", label: "Piki Films"},
  {value: "Plan B Entertainment", label: "Plan B Entertainment"},
  {value: "Platinum Dunes", label: "Platinum Dunes"},
  {value: "PolyGram Filmed Entertainment", label: "PolyGram Filmed Entertainment"},
  {value: "Pretorius Pictures", label: "Pretorius Pictures"},
  {value: "Quiver Distribution", label: "Quiver Distribution"},
  {value: "RADiUS-TWC", label: "RADiUS-TWC"},
  {value: "RCR Distribution", label: "RCR Distribution"},
  {value: "RKO Radio Pictures", label: "RKO Radio Pictures"},
  {value: "RLJ Entertainment", label: "RLJ Entertainment"},
  {value: "Rainmaker Animation", label: "Rainmaker Animation"},
  {value: "Rankin/Bass Productions", label: "Rankin/Bass Productions"},
  {value: "Redbox Entertainment", label: "Redbox Entertainment"},
  {value: "Reel FX Animation", label: "Reel FX Animation"},
  {value: "Regatta", label: "Regatta"},
  {value: "Relativity Media", label: "Relativity Media"},
  {value: "Renaissance Films", label: "Renaissance Films"},
  {value: "Renaissance Pictures", label: "Renaissance Pictures"},
  {value: "Republic Pictures", label: "Republic Pictures"},
  {value: "Rivdel Films", label: "Rivdel Films"},
  {value: "River Road", label: "River Road"},
  {value: "Roadside Attractions", label: "Roadside Attractions"},
  {value: "Rogue Pictures", label: "Rogue Pictures"},
  {value: "Rose & Ruby", label: "Rose & Ruby"},
  {value: "Rosebud Communications", label: "Rosebud Communications"},
  {value: "STX Films", label: "STX Films"},
  {value: "Saban Films", label: "Saban Films"},
  {value: "Safran Company", label: "Safran Company"},
  {value: "Samuel Goldwyn Films", label: "Samuel Goldwyn Films"},
  {value: "Saturn Films", label: "Saturn Films"},
  {value: "Screen Gems", label: "Screen Gems"},
  {value: "Screen Media Films", label: "Screen Media Films"},
  {value: "Searchlights Pictures", label: "Searchlights Pictures"},
  {value: "See-Saw Films", label: "See-Saw Films"},
  {value: "Shining Excalibur Films", label: "Shining Excalibur Films"},
  {value: "Shintoho", label: "Shintoho"},
  {value: "Shochiku", label: "Shochiku"},
  {value: "Shout! Studios", label: "Shout! Studios"},
  {value: "Showbox", label: "Showbox"},
  {value: "Showbox Entertainment", label: "Showbox Entertainment"},
  {value: "Shudder", label: "Shudder"},
  {value: "Signature Entertainment", label: "Signature Entertainment"},
  {value: "Solstice Studios", label: "Solstice Studios"},
  {value: "Sovexportfilm", label: "Sovexportfilm"},
  {value: "Stage 6 Films", label: "Stage 6 Films"},
  {value: "Star Film Company", label: "Star Film Company"},
  {value: "Starz Animation", label: "Starz Animation"},
  {value: "Strand Releasing", label: "Strand Releasing"},
  {value: "StudioCanal", label: "StudioCanal"},
  {value: "Summit Entertainment", label: "Summit Entertainment"},
  {value: "Sundance Institute", label: "Sundance Institute"},
  {value: "Sweetland Films", label: "Sweetland Films"},
  {value: "Syfy Films", label: "Syfy Films"},
  {value: "Syncopy", label: "Syncopy"},
  {value: "THINKFilm", label: "THINKFilm"},
  {value: "TRT", label: "TRT"},
  {value: "Tartan Films", label: "Tartan Films"},
  {value: "The Cinema Guild", label: "The Cinema Guild"},
  {value: "Third Rail Releasing", label: "Third Rail Releasing"},
  {value: "Titanus", label: "Titanus"},
  {value: "Toei Company", label: "Toei Company"},
  {value: "Toho", label: "Toho"},
  {value: "Tokyo Movie Shinsha", label: "Tokyo Movie Shinsha"},
  {value: "Topcraft", label: "Topcraft"},
  {value: "Touchstone Pictures", label: "Touchstone Pictures"},
  {value: "Trans World Entertainment", label: "Trans World Entertainment"},
  {value: "TriArt Film", label: "TriArt Film"},
  {value: "TriStar Pictures", label: "TriStar Pictures"},
  {value: "Tribeca Film", label: "Tribeca Film"},
  {value: "Trimark Pictures", label: "Trimark Pictures"},
  {value: "Turtle Releasing", label: "Turtle Releasing"},
  {value: "Tyler Perry Studios", label: "Tyler Perry Studios"},
  {value: "USA Films", label: "USA Films"},
  {value: "Uncork'd Entertainment", label: "Uncork'd Entertainment"},
  {value: "United Artists", label: "United Artists"},
  {value: "Universal Pictures Platinum Dunes", label: "Universal Pictures Platinum Dunes"},
  {value: "Unviersal Pictures", label: "Unviersal Pictures"},
  {value: "Utopia Pictures", label: "Utopia Pictures"},
  {value: "VHX", label: "VHX"},
  {value: "Vera Films", label: "Vera Films"},
  {value: "Vertical Entertainment", label: "Vertical Entertainment"},
  {value: "Vertigo Films", label: "Vertigo Films"},
  {value: "Vestron Pictures", label: "Vestron Pictures"},
  {value: "Vinod Chopra Films", label: "Vinod Chopra Films"},
  {value: "Vitagraph Studios", label: "Vitagraph Studios"},
  {value: "Vivendi Entertainment", label: "Vivendi Entertainment"},
  {value: "Viz Pictures", label: "Viz Pictures"},
  {value: "Votiv Films", label: "Votiv Films"},
  {value: "WWE Films", label: "WWE Films"},
  {value: "Wandering Trail Pictures", label: "Wandering Trail Pictures"},
  {value: "Well Go USA", label: "Well Go USA"},
  {value: "Werner Herzog Filmproduktion", label: "Werner Herzog Filmproduktion"},
  {value: "Wild Bunch", label: "Wild Bunch"},
  {value: "Wild Eye Releasing", label: "Wild Eye Releasing"},
  {value: "Wiseau-Films", label: "Wiseau-Films"},
  {value: "Working Title", label: "Working Title"},
  {value: "X Filme", label: "X Filme"},
  {value: "X-Filme Creative Pool", label: "X-Filme Creative Pool"},
  {value: "XYZ Films", label: "XYZ Films"},
  {value: "Xlrator Media", label: "Xlrator Media"},
  {value: "Xstream Pictures", label: "Xstream Pictures"},
  {value: "Yari Film Group", label: "Yari Film Group"},
  {value: "Zentropa Entertainments", label: "Zentropa Entertainments"},
  {value: "Zespol Filmowy", label: "Zespol Filmowy"},
]

export const studiocompanyOptions: object[] = [
  {
    label: 'Featured',
    options: studiocompanyFeatured,
  },
  {
    label: 'Other',
    options: studiocompanyOther,
  },
]

export const universeFeatured: DropdownOption[] = [
  { value: 'Adam Sandler-verse', label: 'Adam Sandler-verse' },
  { value: 'A Quiet Place Franchise', label: 'A Quiet Place Franchise'},
  { value: 'Alien Universe', label: 'Alien Universe' },
  { value: 'Bourne Universe', label: 'Bourne Universe' },
  { value: 'Coen Brothers Universe', label: 'Coen Brothers Universe' },
  { value: 'Fast & Furious Universe', label: 'Fast & Furious Universe' },
  { value: 'James Bond Collection', label: 'James Bond Collection' },
  { value: 'Judd Apatow Universe', label: 'Judd Apatow Universe' },
  { value: 'Jurassic Park Franchise', label: 'Jurassic Park Franchise' },
  { value: "Mission: Impossible Franchise", label: "Mission: Impossible Franchise"},
  { value: 'Netflix Original', label: 'Netflix Original' },
  { value: "Ocean's Franchise", label: "Ocean's Franchise" },
  { value: "Planet of the Apes Universe", label: "Planet of the Apes Universe"},  { value: 'Rocky Franchise', label: 'Rocky Franchise' },
  { value: "Rocky Franchise", label: "Rocky Franchise"},
  { value: 'Shrek Universe', label: 'Shrek Universe' },
  { value: "Star Trek Universe", label: "Star Trek Universe"},
  { value: 'Stephen King Universe', label: 'Stephen King Universe' },
  { value: "Taylor Sheridan Universe", label: "Taylor Sheridan Universe"},
  { value: 'Terminator Franchise', label: 'Terminator Franchise' },
  { value: "Transformers Universe", label: "Transformers Universe"},
  { value: 'Tyler Perry-verse', label: 'Tyler Perry-verse' },
]

const universeMarvel: DropdownOption[] = [
  { value: 'Marvel (MCU)', label: 'Marvel (MCU)' },
  { value: 'Marvel (Non-MCU)', label: 'Marvel (Non-MCU)' },
  { value: 'Marvel (Sony Pictures)', label: 'Marvel (Sony Pictures)' },
  { value: 'Marvel (X-Men)', label: 'Marvel (X-Men)' },
]

const universeDC: DropdownOption[] = [
  {value: "DC (Animated - DCAMU)", label: "DC (Animated - DCAMU)"},
  { value: 'DC (DCEU)', label: 'DC (DCEU)' },
  { value: 'DC (Non-DCEU)', label: 'DC (Non-DCEU)' },
  {value: "Dark Knight Trilogy", label: "Dark Knight Trilogy"},
  {value: "Superman (Original Universe)", label: "Superman (Original Universe)"},
  {value: "Tim Burton Batman Series", label: "Tim Burton Batman Series"},
]

const universeStarWars: DropdownOption[] = [
  {value: "Star Wars Universe", label: "Star Wars Universe"},
  {value: "Star Wars Original Trilogy", label: "Star Wars Original Trilogy"},
  {value: "Star Wars Prequel Trilogy", label: "Star Wars Prequel Trilogy"},
  {value: "Star Wars Sequel Trilogy", label: "Star Wars Sequel Trilogy"},
  {value: "Star Wars Standalone", label: "Star Wars Standalone"},
]

const universeDisney: DropdownOption[] = [
  { value: 'Disney Animated', label: 'Disney Animated' },
  { value: 'Disney Animation Studios', label: 'Disney Animation Studios' },
  { value: 'Pixar', label: 'Disney Pixar' },
  { value: 'Disney Live-Action', label: 'Disney Live-Action' },
  { value: 'Disney Live-Action Remake', label: 'Disney Live-Action Remake' },
  {
    value: 'Disney Channel Original Movie',
    label: 'Disney Channel Original Movie',
  },
  {value: "Disney+", label: "Disney+"},
  {value: "Muppets", label: "Muppets"},
  {value: "Pirates of the Caribbean", label: "Pirates of the Caribbean"},
]

const universeLOTR: DropdownOption[] = [
  { value: 'Middle-earth', label: 'Middle-earth (Lord of the Rings)' },
  {value: "Lord of the Rings Trilogy", label: "Lord of the Rings Trilogy"},
  {value: "Hobbit Trilogy", label: "Hobbit Trilogy"},
]

const universeWizardWorld: DropdownOption[] = [
  {
    value: 'Wizarding World (Harry Potter)',
    label: 'Wizarding World (Harry Potter)',
  },
  {value: "Harry Potter Franchise", label: "Harry Potter Franchise"},
  {value: "Fantastic Beasts Franchise", label: "Fantastic Beasts Franchise"},
]

const universeOther: DropdownOption[] = [
  {value: "A Nightmare on Elm Street", label: "A Nightmare on Elm Street"},
  {value: "Aaron Sorkin Universe", label: "Aaron Sorkin Universe"},
  {value: "Ace Ventura", label: "Ace Ventura"},
  {value: "Addams Family", label: "Addams Family"},
  {value: "Airplane!", label: "Airplane!"},
  {value: "Alien vs. Predator", label: "Alien vs. Predator"},
  {value: "Almighty Franchise", label: "Almighty Franchise"},
  {value: "Amazon Prime Original", label: "Amazon Prime Original"},
  {value: "American Pie", label: "American Pie"},
  {value: "Amityville", label: "Amityville"},
  {value: "Analyze This Series", label: "Analyze This Series"},
  {value: "Anchorman", label: "Anchorman"},
  {value: "Animated Christmas", label: "Animated Christmas"},
  {value: "Ant-Man", label: "Ant-Man"},
  {value: "Apocalypse Trilogy", label: "Apocalypse Trilogy"},
  {value: "Apple TV+ Original", label: "Apple TV+ Original"},
  {value: "Arthur", label: "Arthur"},
  {value: "Austin Powers", label: "Austin Powers"},
  {value: "Avengers", label: "Avengers"},
  {value: "Babe", label: "Babe"},
  {value: "Baby Geniuses", label: "Baby Geniuses"},
  {value: "Back to the Future", label: "Back to the Future"},
  {value: "Bad Boys", label: "Bad Boys"},
  {value: "Bad News Bears", label: "Bad News Bears"},
  {value: "Bad Santa Series", label: "Bad Santa Series"},
  {value: "Barbershop", label: "Barbershop"},
  {value: "Before Trilogy", label: "Before Trilogy"},
  {value: "Benson & Moorhead Universe", label: "Benson & Moorhead Universe"},
  {value: "Beverly Hills Cop", label: "Beverly Hills Cop"},
  {value: "Big Momma's House", label: "Big Momma's House"},
  {value: "Bill & Ted", label: "Bill & Ted"},
  {value: "Black Christmas Series", label: "Black Christmas Series"},
  {value: "Blade Runner", label: "Blade Runner"},
  {value: "Blair Witch", label: "Blair Witch"},
  {value: "Blue Sky Universe", label: "Blue Sky Universe"},
  {value: "Blues Brothers Franchise", label: "Blues Brothers Franchise"},
  {value: "Blumhouse", label: "Blumhouse"},
  {value: "Boondock Saints", label: "Boondock Saints"},
  {value: "Borat Franchise", label: "Borat Franchise"},
  {value: "Boss Baby Universe", label: "Boss Baby Universe"},
  {value: "Brady Bunch", label: "Brady Bunch"},
  {value: "Brahms: The Boy", label: "Brahms: The Boy"},
  {value: "Bridget Jones", label: "Bridget Jones"},
  {value: "Bring It On", label: "Bring It On"},
  {value: "Broken Lizard", label: "Broken Lizard"},
  {value: "Captain America", label: "Captain America"},
  {value: "Carrie Franchise", label: "Carrie Franchise"},
  {value: "Cars Trilogy", label: "Cars Trilogy"},
  {value: "Cats & Dogs Series", label: "Cats & Dogs Series"},
  {value: "Charlie Kaufman", label: "Charlie Kaufman"},
  {value: "Charlie's Angels", label: "Charlie's Angels"},
  {value: "Child's Play", label: "Child's Play"},
  {value: "Christmas Chronicles Series", label: "Christmas Chronicles Series"},
  {value: "Chronicles of Riddick", label: "Chronicles of Riddick"},
  {value: "Cloverfield", label: "Cloverfield"},
  {value: "Collector Franchise", label: "Collector Franchise"},
  {value: "Coming To America", label: "Coming To America"},
  {value: "Conjuring Universe", label: "Conjuring Universe"},
  {value: "Crank Franchise", label: "Crank Franchise"},
  {value: "Critters Franchise", label: "Critters Franchise"},
  {value: "Croods Universe", label: "Croods Universe"},
  {value: "Da Vinci Code Trilogy", label: "Da Vinci Code Trilogy"},
  {value: "Daddy Universe", label: "Daddy Universe"},
  {value: "Dark Universe", label: "Dark Universe"},
  {value: "Death Race", label: "Death Race"},
  {value: "Diary of a Wimpy Kid", label: "Diary of a Wimpy Kid"},
  {value: "Die Hard", label: "Die Hard"},
  {value: "Dirty Harry", label: "Dirty Harry"},
  {value: "Disney Theme Park Rides", label: "Disney Theme Park Rides"},
  {value: "Divergent Series", label: "Divergent Series"},
  {value: "Dollars Trilogy", label: "Dollars Trilogy"},
  {value: "Dolphin Tale Series", label: "Dolphin Tale Series"},
  {value: "Dr. Dolittle", label: "Dr. Dolittle"},
  {value: "Dr. Seuss", label: "Dr. Seuss"},
  {value: "Dragon Ball Z", label: "Dragon Ball Z"},
  {value: "Dragon Tattoo Stories", label: "Dragon Tattoo Stories"},
  {value: "Dumb and Dumber", label: "Dumb and Dumber"},
  {value: "Elite Squad", label: "Elite Squad"},
  {value: "Equalizer Franchise", label: "Equalizer Franchise"},
  {value: "Ernest Franchise", label: "Ernest Franchise"},
  {value: "Escape From Series", label: "Escape From Series"},
  {value: "Escape Plan Series", label: "Escape Plan Series"},
  {value: "Escape Room Series", label: "Escape Room Series"},
  {value: "Evil Dead", label: "Evil Dead"},
  {value: "Expendables Franchise", label: "Expendables Franchise"},
  {value: "Fantastic Four", label: "Fantastic Four"},
  {value: "Fear Street Series", label: "Fear Street Series"},
  {value: "Fievel", label: "Fievel"},
  {value: "Fifty Shades Trilogy", label: "Fifty Shades Trilogy"},
  {value: "Final Destination", label: "Final Destination"},
  {value: "Final Fantasy", label: "Final Fantasy"},
  {value: "Finding Nemo", label: "Finding Nemo"},
  {value: "Firefly Series (Rob Zombie)", label: "Firefly Series (Rob Zombie)"},
  {value: "Flatliners", label: "Flatliners"},
  {value: "Fletch", label: "Fletch"},
  {value: "Footloose", label: "Footloose"},
  {value: "Friday Series", label: "Friday Series"},
  {value: "Friday the 13th", label: "Friday the 13th"},
  {value: "Frozen Franchise", label: "Frozen Franchise"},
  {value: "G.I. Joe Universe", label: "G.I. Joe Universe"},
  {value: "Garfield Universe", label: "Garfield Universe"},
  {value: "Ghost Rider", label: "Ghost Rider"},
  {value: "Ghost in the Shell", label: "Ghost in the Shell"},
  {value: "Ghostbusters", label: "Ghostbusters"},
  {value: "Gnomes", label: "Gnomes"},
  {value: "Godfather", label: "Godfather"},
  {value: "Godzilla Franchise", label: "Godzilla Franchise"},
  {value: "Goosebumps Series", label: "Goosebumps Series"},
  {value: "Gremlins", label: "Gremlins"},
  {value: "Grudge Film Series", label: "Grudge Film Series"},
  {value: "Guardians of the Galaxy", label: "Guardians of the Galaxy"},
  {value: "HBO Max", label: "HBO Max"},
  {value: "Halloween", label: "Halloween"},
  {value: "Hangover Trilogy", label: "Hangover Trilogy"},
  {value: "Hanna-Barbera", label: "Hanna-Barbera"},
  {value: "Hannibal Lecter", label: "Hannibal Lecter"},
  {value: "Happy Death Day", label: "Happy Death Day"},
  {value: "Harold & Kumar", label: "Harold & Kumar"},
  {value: "Has Fallen Franchise", label: "Has Fallen Franchise"},
  {value: "Hellboy", label: "Hellboy"},
  {value: "Hellraiser Franchise", label: "Hellraiser Franchise"},
  {value: "Highlander", label: "Highlander"},
  {value: "Hills Have Eyes", label: "Hills Have Eyes"},
  {value: "Hitman", label: "Hitman"},
  {value: "Hitman's Bodyguard Series", label: "Hitman's Bodyguard Series"},
  {value: "Home Alone Trilogy", label: "Home Alone Trilogy"},
  {value: "Honey I Shrunk", label: "Honey I Shrunk"},
  {value: "Horrible Bosses Series", label: "Horrible Bosses Series"},
  {value: "Hostel Franchise", label: "Hostel Franchise"},
  {value: "Hot Tub Time Machine", label: "Hot Tub Time Machine"},
  {value: "Hotel Transylvania", label: "Hotel Transylvania"},
  {value: "How To Train Your Dragon", label: "How To Train Your Dragon"},
  {value: "Hulk", label: "Hulk"},
  {value: "Human Centipede", label: "Human Centipede"},
  {value: "Hunger Games", label: "Hunger Games"},
  {value: "Hustler Franchise", label: "Hustler Franchise"},
  {value: "Ice Age", label: "Ice Age"},
  {value: "Illumination Universe", label: "Illumination Universe"},
  {value: "Incredibles", label: "Incredibles"},
  {value: "Independence Day", label: "Independence Day"},
  {value: "Indiana Jones", label: "Indiana Jones"},
  {value: "Insidious", label: "Insidious"},
  {value: "Iron Man", label: "Iron Man"},
  {value: "It (Pennywise) Universe", label: "It (Pennywise) Universe"},
  {value: "Jack Reacher Series", label: "Jack Reacher Series"},
  {value: "Jack Ryan (Ryanverse)", label: "Jack Ryan (Ryanverse)"},
  {value: "Jackass", label: "Jackass"},
  {value: "Jacob's Ladder Series", label: "Jacob's Ladder Series"},
  {value: "James Bond - Brosnan", label: "James Bond - Brosnan"},
  {value: "James Bond - Connery", label: "James Bond - Connery"},
  {value: "James Bond - Craig", label: "James Bond - Craig"},
  {value: "James Bond - Dalton", label: "James Bond - Dalton"},
  {value: "James Bond - Lazenby", label: "James Bond - Lazenby"},
  {value: "James Bond - Moore", label: "James Bond - Moore"},
  {value: "James Bond - Niven", label: "James Bond - Niven"},
  {value: "Jaws", label: "Jaws"},
  {value: "Jeepers Creepers", label: "Jeepers Creepers"},
  {value: "John Grisham-verse", label: "John Grisham-verse"},
  {value: "John Hughes (Shermerverse)", label: "John Hughes (Shermerverse)"},
  {value: "John Wick", label: "John Wick"},
  {value: "Johnny English", label: "Johnny English"},
  {value: "Journey To Franchise", label: "Journey To Franchise"},
  {value: "Judge Dredd", label: "Judge Dredd"},
  {value: "Jumanji", label: "Jumanji"},
  {value: "Jump Street", label: "Jump Street"},
  {value: "Jurassic Park Original Trilogy", label: "Jurassic Park Original Trilogy"},
  {value: "Jurassic Park Sequel Trilogy", label: "Jurassic Park Sequel Trilogy"},
  {value: "Karate Kid", label: "Karate Kid"},
  {value: "Kick-Ass", label: "Kick-Ass"},
  {value: "Kissing Booth Franchise", label: "Kissing Booth Franchise"},
  {value: "Kung Fu Panda", label: "Kung Fu Panda"},
  {value: "LEGO", label: "LEGO"},
  {value: "Last Summer Series", label: "Last Summer Series"},
  {value: "Legally Blonde", label: "Legally Blonde"},
  {value: "Leprechaun", label: "Leprechaun"},
  {value: "Lethal Weapon", label: "Lethal Weapon"},
  {value: "Living Dead Series", label: "Living Dead Series"},
  {value: "Lonely Island", label: "Lonely Island"},
  {value: "Look Who's Talking Trilogy", label: "Look Who's Talking Trilogy"},
  {value: "Looney Tunes", label: "Looney Tunes"},
  {value: "MGM Studios", label: "MGM Studios"},
  {value: "Mad Max", label: "Mad Max"},
  {value: "Madagascar", label: "Madagascar"},
  {value: "Major League", label: "Major League"},
  {value: "Mamma Mia!", label: "Mamma Mia!"},
  {value: "Mary Poppins", label: "Mary Poppins"},
  {value: "Matrix Trilogy", label: "Matrix Trilogy"},
  {value: "Maze Runner Series", label: "Maze Runner Series"},
  {value: "Meet the Parents", label: "Meet the Parents"},
  {value: "Men in Black", label: "Men in Black"},
  {value: "Mighty Ducks", label: "Mighty Ducks"},
  {value: "Minions", label: "Minions"},
  {value: "MonsterVerse", label: "MonsterVerse"},
  {value: "Monsters Inc.", label: "Monsters Inc."},
  {value: "Monty Python", label: "Monty Python"},
  {value: "Mortal Kombat Franchise", label: "Mortal Kombat Franchise"},
  {value: "Mr. Bean", label: "Mr. Bean"},
  {value: "Mummy", label: "Mummy"},
  {value: "Naked Gun", label: "Naked Gun"},
  {value: "Narnia", label: "Narnia"},
  {value: "National Lampoon", label: "National Lampoon"},
  {value: "Netflix Christmas", label: "Netflix Christmas"},
  {value: "Nicholas Sparks", label: "Nicholas Sparks"},
  {value: "Nickelodeon", label: "Nickelodeon"},
  {value: "Ninja Turtles", label: "Ninja Turtles"},
  {value: "Nutty Professor", label: "Nutty Professor"},
  {value: "Omen Franchise", label: "Omen Franchise"},
  {value: "Ouija Series", label: "Ouija Series"},
  {value: "Outrage Trilogy", label: "Outrage Trilogy"},
  {value: "Paramount+ Original", label: "Paramount+ Original"},
  {value: "Paranormal Activity", label: "Paranormal Activity"},
  {value: "Pathé Animation", label: "Pathé Animation"},
  {value: "Peanuts Universe", label: "Peanuts Universe"},
  {value: "Percy Jackson Series", label: "Percy Jackson Series"},
  {value: "Peter Rabbit Series", label: "Peter Rabbit Series"},
  {value: "Pink Panther", label: "Pink Panther"},
  {value: "Pitch Perfect", label: "Pitch Perfect"},
  {value: "Planet of the Apes (New)", label: "Planet of the Apes (New)"},
  {value: "Planet of the Apes (Old)", label: "Planet of the Apes (Old)"},
  {value: "PlayStation", label: "PlayStation"},
  {value: "Pokemon Franchise", label: "Pokemon Franchise"},
  {value: "Predator", label: "Predator"},
  {value: "Public Domain", label: "Public Domain"},
  {value: "Punisher", label: "Punisher"},
  {value: "Purge Franchise", label: "Purge Franchise"},
  {value: "Pusher Trilogy", label: "Pusher Trilogy"},
  {value: "Raid Franchise", label: "Raid Franchise"},
  {value: "Rambo", label: "Rambo"},
  {value: "Resident Evil", label: "Resident Evil"},
  {value: "Revenge of the Nerds", label: "Revenge of the Nerds"},
  {value: "Ring Series", label: "Ring Series"},
  {value: "Rugrats", label: "Rugrats"},
  {value: "Rush Hour", label: "Rush Hour"},
  {value: "Saturday Night Live", label: "Saturday Night Live"},
  {value: "Saw", label: "Saw"},
  {value: "Scary Movie", label: "Scary Movie"},
  {value: "Scream", label: "Scream"},
  {value: "Screen Media Films", label: "Screen Media Films"},
  {value: "Secret Life of Pets", label: "Secret Life of Pets"},
  {value: "Sex and the City", label: "Sex and the City"},
  {value: "Shakespeare Universe", label: "Shakespeare Universe"},
  {value: "Shanghai Series", label: "Shanghai Series"},
  {value: "Shining Series", label: "Shining Series"},
  {value: "Sin City", label: "Sin City"},
  {value: "Sinister", label: "Sinister"},
  {value: "Smurfs", label: "Smurfs"},
  {value: "Snow White", label: "Snow White"},
  {value: "Space Jam Series", label: "Space Jam Series"},
  {value: "Speed Franchise", label: "Speed Franchise"},
  {value: "Spider-Man", label: "Spider-Man"},
  {value: "Spirit the Stallion", label: "Spirit the Stallion"},
  {value: "SpongeBob", label: "SpongeBob"},
  {value: "Spy Kids", label: "Spy Kids"},
  {value: "Star Trek Kelvin Timline", label: "Star Trek Kelvin Timline"},
  {value: "Star Trek Next Generation", label: "Star Trek Next Generation"},
  {value: "Star Trek Original Series", label: "Star Trek Original Series"},
  {value: "Teen Wolf", label: "Teen Wolf"},
  {value: "Texas Chain Saw", label: "Texas Chain Saw"},
  {value: "Thor", label: "Thor"},
  {value: "Three Flavours Cornetto", label: "Three Flavours Cornetto"},
  {value: "To All the Boys Trilogy", label: "To All the Boys Trilogy"},
  {value: "Tomb Raider", label: "Tomb Raider"},
  {value: "Toy Story Franchise", label: "Toy Story Franchise"},
  {value: "Trainspotting", label: "Trainspotting"},
  {value: "Transformers Michael Bay", label: "Transformers Michael Bay"},
  {value: "Transporter", label: "Transporter"},
  {value: "Tremors Franchise", label: "Tremors Franchise"},
  {value: "Trip Franchise", label: "Trip Franchise"},
  {value: "Trolls", label: "Trolls"},
  {value: "Tron", label: "Tron"},
  {value: "Twilight", label: "Twilight"},
  {value: "Unbreakable Trilogy", label: "Unbreakable Trilogy"},
  {value: "Underworld", label: "Underworld"},
  {value: "Unfriended", label: "Unfriended"},
  {value: "V/H/S Series", label: "V/H/S Series"},
  {value: "Vacation Series", label: "Vacation Series"},
  {value: "Valiant Comics", label: "Valiant Comics"},
  {value: "View Askewniverse", label: "View Askewniverse"},
  {value: "Wall Street Series", label: "Wall Street Series"},
  {value: "Weekend at Bernie's", label: "Weekend at Bernie's"},
  {value: "Whole Yards Series", label: "Whole Yards Series"},
  {value: "Wolf Warrior Series", label: "Wolf Warrior Series"},
  {value: "Wreck-It Ralph", label: "Wreck-It Ralph"},
  {value: "Wrong Turn Franchise", label: "Wrong Turn Franchise"},
  {value: "Zombieland", label: "Zombieland"},
  {value: "Zoolander", label: "Zoolander"},
  {value: "Zorro", label: "Zorro"},
  {value: "xXx", label: "xXx"},
]

export const universeOptions: object[] = [
  {
    label: 'Marvel',
    options: universeMarvel,
  },
  {
    label: 'DC',
    options: universeDC,
  },
  {
    label: 'Star Wars',
    options: universeStarWars,
  },
  {
    label: 'Disney',
    options: universeDisney,
  },
  {
    label: 'Lord of The Rings',
    options: universeLOTR,
  },
  {
    label: 'Wizarding World',
    options: universeWizardWorld,
  },
  {
    label: 'Featured',
    options: universeFeatured,
  },
  {
    label: 'Other Universes',
    options: universeOther,
  },
]

export const countryOptions: DropdownOption[] = [
  {value: "Argentina", label: "Argentina"},
  {value: "Australia", label: "Australia"},
  {value: "Austria", label: "Austria"},
  {value: "Belgium", label: "Belgium"},
  {value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina"},
  {value: "Brazil", label: "Brazil"},
  {value: "Canada", label: "Canada"},
  {value: "Chile", label: "Chile"},
  {value: "China", label: "China"},
  {value: "Denmark", label: "Denmark"},
  {value: "England", label: "England"},
  {value: "Finland", label: "Finland"},
  {value: "France", label: "France"},
  {value: "Germany", label: "Germany"},
  {value: "Greece", label: "Greece"},
  {value: "Hong Kong", label: "Hong Kong"},
  {value: "India", label: "India"},
  {value: "Indonesia", label: "Indonesia"},
  {value: "Ireland", label: "Ireland"},
  {value: "Israel", label: "Israel"},
  {value: "Italy", label: "Italy"},
  {value: "Japan", label: "Japan"},
  {value: "Mexico", label: "Mexico"},
  {value: "New Zealand", label: "New Zealand"},
  {value: "Norway", label: "Norway"},
  {value: "Polan", label: "Polan"},
  {value: "Poland", label: "Poland"},
  {value: "Russia", label: "Russia"},
  {value: "Serbia", label: "Serbia"},
  {value: "South Korea", label: "South Korea"},
  {value: "Spain", label: "Spain"},
  {value: "Sweden", label: "Sweden"},
  {value: "Taiwan", label: "Taiwan"},
  {value: "Thailand", label: "Thailand"},
  {value: "United Kingdom", label: "United Kingdom"},
]

export const characterOptions: DropdownOption[] = [
  {value: "Adam Sandler", label: "Adam Sandler"},
{value: "Ant-Man", label: "Ant-Man"},
{value: "Aquaman", label: "Aquaman"},
{value: "Avengers", label: "Avengers"},
{value: "Batman", label: "Batman"},
{value: "Black Panther", label: "Black Panther"},
{value: "Black Widow", label: "Black Widow"},
{value: "Blade", label: "Blade"},
{value: "Bruce Lee", label: "Bruce Lee"},
{value: "Captain America", label: "Captain America"},
{value: "Captain Marvel", label: "Captain Marvel"},
{value: "Cat in the Hat", label: "Cat in the Hat"},
{value: "Catwoman", label: "Catwoman"},
{value: "Chucky", label: "Chucky"},
{value: "Constantine", label: "Constantine"},
{value: "Creed", label: "Creed"},
{value: "Cyborg", label: "Cyborg"},
{value: "Damien Omen", label: "Damien Omen"},
{value: "Daredevil", label: "Daredevil"},
{value: "Deadpool", label: "Deadpool"},
{value: "Doctor Strange", label: "Doctor Strange"},
{value: "Dracula", label: "Dracula"},
{value: "Elektra", label: "Elektra"},
{value: "Eternals", label: "Eternals"},
{value: "Falcon", label: "Falcon"},
{value: "Fantastic Four", label: "Fantastic Four"},
{value: "Flash", label: "Flash"},
{value: "Flash Gordon", label: "Flash Gordon"},
{value: "Flintstones", label: "Flintstones"},
{value: "Frankenstein", label: "Frankenstein"},
{value: "Freddy Krueger", label: "Freddy Krueger"},
{value: "Ghost Rider", label: "Ghost Rider"},
{value: "Godzilla", label: "Godzilla"},
{value: "Green Lantern", label: "Green Lantern"},
{value: "Grinch", label: "Grinch"},
{value: "Guardians of the Galaxy", label: "Guardians of the Galaxy"},
{value: "Harley Quinn", label: "Harley Quinn"},
{value: "Hawkeye", label: "Hawkeye"},
{value: "Hellboy", label: "Hellboy"},
{value: "Howard the Duck", label: "Howard the Duck"},
{value: "Hulk", label: "Hulk"},
{value: "Indiana Jones", label: "Indiana Jones"},
{value: "Invisible Man", label: "Invisible Man"},
{value: "Iron Man", label: "Iron Man"},
{value: "James Bond", label: "James Bond"},
{value: "Jason Voorhees", label: "Jason Voorhees"},
{value: "Jaws", label: "Jaws"},
{value: "Jigsaw", label: "Jigsaw"},
{value: "Johnny English", label: "Johnny English"},
{value: "Joker", label: "Joker"},
{value: "Jonah Hex", label: "Jonah Hex"},
{value: "Justice League", label: "Justice League"},
{value: "King Kong", label: "King Kong"},
{value: "Lara Croft", label: "Lara Croft"},
{value: "Leatherface", label: "Leatherface"},
{value: "Leprechaun", label: "Leprechaun"},
{value: "Loki", label: "Loki"},
{value: "Looney Tunes", label: "Looney Tunes"},
{value: "Magneto", label: "Magneto"},
{value: "Man with No Name", label: "Man with No Name"},
{value: "Michael Myers", label: "Michael Myers"},
{value: "Mr. Bean", label: "Mr. Bean"},
{value: "Mummy", label: "Mummy"},
{value: "Nic Cage", label: "Nic Cage"},
{value: "Nick Fury", label: "Nick Fury"},
{value: "Nutty Professor", label: "Nutty Professor"},
{value: "Paul Blart", label: "Paul Blart"},
{value: "Pee-wee", label: "Pee-wee"},
{value: "Pennywise", label: "Pennywise"},
{value: "Pinhead", label: "Pinhead"},
{value: "Pink Panther", label: "Pink Panther"},
{value: "Predator", label: "Predator"},
{value: "Professor X", label: "Professor X"},
{value: "Professor X", label: "Professor X"},
{value: "Punisher", label: "Punisher"},
{value: "Quicksilver", label: "Quicksilver"},
{value: "Rambo", label: "Rambo"},
{value: "Riddick", label: "Riddick"},
{value: "Rocky Balboa", label: "Rocky Balboa"},
{value: "Ron Burgundy", label: "Ron Burgundy"},
{value: "Scarlet Witch", label: "Scarlet Witch"},
{value: "Scooby-Doo", label: "Scooby-Doo"},
{value: "Shang-Chi", label: "Shang-Chi"},
{value: "Shazam!", label: "Shazam!"},
{value: "Sherlock Holmes", label: "Sherlock Holmes"},
{value: "Shrek", label: "Shrek"},
{value: "Simpsons", label: "Simpsons"},
{value: "Snake Plissken", label: "Snake Plissken"},
{value: "Spider-Man", label: "Spider-Man"},
{value: "Stu Feiner", label: "Stu Feiner"},
{value: "Suicide Squad", label: "Suicide Squad"},
{value: "Supergirl", label: "Supergirl"},
{value: "Superman", label: "Superman"},
{value: "Swamp Thing", label: "Swamp Thing"},
{value: "Teen Titans", label: "Teen Titans"},
{value: "Thanos", label: "Thanos"},
{value: "The Wasp", label: "The Wasp"},
{value: "Thor", label: "Thor"},
{value: "Van Helsing", label: "Van Helsing"},
{value: "Venom", label: "Venom"},
{value: "Vision", label: "Vision"},
{value: "War Machine", label: "War Machine"},
{value: "Willy Wonka", label: "Willy Wonka"},
{value: "Winter Soldier", label: "Winter Soldier"},
{value: "Wolf Man", label: "Wolf Man"},
{value: "Wolfman", label: "Wolfman"},
{value: "Wolverine", label: "Wolverine"},
{value: "Wonder Woman", label: "Wonder Woman"},
{value: "X-Men", label: "X-Men"},
{value: "Xander Cage", label: "Xander Cage"},
]

const sportOptions: DropdownOption[] = [
  {value: "Baseball", label: "Baseball"},
  {value: "Basketball", label: "Basketball"},
  {value: "Billiards", label: "Billiards"},
  {value: "Bowling", label: "Bowling"},
  {value: "Boxing", label: "Boxing"},
  {value: "Cheerleading", label: "Cheerleading"},
  {value: "Chess", label: "Chess"},
  {value: "Dodgeball", label: "Dodgeball"},
  {value: "Football", label: "Football"},
  {value: "Golf", label: "Golf"},
  {value: "Halloween", label: "Halloween"},
  {value: "Hockey", label: "Hockey"},
  {value: "Horse Racing", label: "Horse Racing"},
  {value: "Martial Arts", label: "Martial Arts"},
  {value: "Olympics", label: "Olympics"},
  {value: "Poker", label: "Poker"},
  {value: "Racing", label: "Racing"},
  {value: "Rugby", label: "Rugby"},
  {value: "Running", label: "Running"},
  {value: "Soccer", label: "Soccer"},
  {value: "Surfing", label: "Surfing"},
  {value: "Table Tennis", label: "Table Tennis"},
  {value: "Tennis", label: "Tennis"},
  {value: "Volleyball", label: "Volleyball"},
  {value: "Wrestling", label: "Wrestling"},
  {value: "X-Games", label: "X-Games"},
]

const holidayOptions: DropdownOption[] = [
  {value: "Christmas", label: "Christmas"},
  {value: "Halloween", label: "Halloween"},
  {value: "New Year's Eve", label: "New Year's Eve"},
  {value: "Valentine's Day", label: "Valentine's Day"},
]

export const sportholidayOptions: object[] = [
  {
    label: 'Holidays',
    options: holidayOptions,
  },
  {
    label: 'Sports',
    options: sportOptions,
  },
]

export const yearOptions: DropdownOption[] = [
  { value: '2021', label: '2021' },
  { value: '2020', label: '2020' },
  { value: '2019', label: '2019' },
  { value: '2018', label: '2018' },
  { value: '2017', label: '2017' },
  { value: '2016', label: '2016' },
  { value: '2015', label: '2015' },
  { value: '2014', label: '2014' },
  { value: '2013', label: '2013' },
  { value: '2012', label: '2012' },
  { value: '2011', label: '2011' },
  { value: '2010', label: '2010' },
  { value: '2009', label: '2009' },
  { value: '2008', label: '2008' },
  { value: '2007', label: '2007' },
  { value: '2006', label: '2006' },
  { value: '2005', label: '2005' },
  { value: '2004', label: '2004' },
  { value: '2003', label: '2003' },
  { value: '2002', label: '2002' },
  { value: '2001', label: '2001' },
  { value: '2000', label: '2000' },
  { value: '1999', label: '1999' },
  { value: '1998', label: '1998' },
  { value: '1997', label: '1997' },
  { value: '1996', label: '1996' },
  { value: '1995', label: '1995' },
  { value: '1994', label: '1994' },
  { value: '1993', label: '1993' },
  { value: '1992', label: '1992' },
  { value: '1991', label: '1991' },
  { value: '1990', label: '1990' },
  { value: '1989', label: '1989' },
  { value: '1988', label: '1988' },
  { value: '1987', label: '1987' },
  { value: '1986', label: '1986' },
  { value: '1985', label: '1985' },
  { value: '1984', label: '1984' },
  { value: '1983', label: '1983' },
  { value: '1982', label: '1982' },
  { value: '1981', label: '1981' },
  { value: '1980', label: '1980' },
  { value: '1979', label: '1979' },
  { value: '1978', label: '1978' },
  { value: '1977', label: '1977' },
  { value: '1976', label: '1976' },
  { value: '1975', label: '1975' },
  { value: '1974', label: '1974' },
  { value: '1973', label: '1973' },
  { value: '1972', label: '1972' },
  { value: '1971', label: '1971' },
  { value: '1970', label: '1970' },
  { value: '1969', label: '1969' },
  { value: '1968', label: '1968' },
  { value: '1967', label: '1967' },
  { value: '1966', label: '1966' },
  { value: '1965', label: '1965' },
  { value: '1964', label: '1964' },
  { value: '1963', label: '1963' },
  { value: '1962', label: '1962' },
  { value: '1961', label: '1961' },
  { value: '1960', label: '1960' },
  { value: '1959', label: '1959' },
  { value: '1958', label: '1958' },
  { value: '1957', label: '1957' },
  { value: '1956', label: '1956' },
  { value: '1955', label: '1955' },
  { value: '1954', label: '1954' },
  { value: '1953', label: '1953' },
  { value: '1952', label: '1952' },
  { value: '1951', label: '1951' },
  { value: '1950', label: '1950' },
  { value: '1949', label: '1949' },
  { value: '1948', label: '1948' },
  { value: '1947', label: '1947' },
  { value: '1946', label: '1946' },
  { value: '1945', label: '1945' },
  { value: '1944', label: '1944' },
  { value: '1943', label: '1943' },
  { value: '1942', label: '1942' },
  { value: '1941', label: '1941' },
  { value: '1940', label: '1940' },
  { value: '1939', label: '1939' },
  { value: '1938', label: '1938' },
  { value: '1937', label: '1937' },
  { value: '1936', label: '1936' },
  { value: '1935', label: '1935' },
  { value: '1934', label: '1934' },
  { value: '1933', label: '1933' },
  { value: '1932', label: '1932' },
  { value: '1931', label: '1930' },
  { value: '1930', label: '1931' },
  { value: '1927', label: '1927' },
  { value: '1925', label: '1925' },
  { value: '1902', label: '1902' },
]

export const decadeOptions: DropdownOption[] = [
  {value: "1930-1939", label: "1930-1939"},
  {value: "1940-1949", label: "1940-1949"},
  {value: "1950-1959", label: "1950-1959"},
  {value: "1960-1969", label: "1960-1969"},
  {value: "1970-1979", label: "1970-1979"},
  {value: "1980-1989", label: "1980-1989"},
  {value: "1990-1999", label: "1990-1999"},
  {value: "2000-2009", label: "2000-2009"},
  {value: "2010-2019", label: "2010-2019"},
  {value: "2020-2029", label: "2020-2029"},
]

export const provider_names: { [key: string]: string } = {
  '9': 'Amazon (Stream)',
  '350': 'Apple TV',
  '289': 'Cinemax',
  '258': 'Critereon',
  '337': 'Disney+',
  '34': 'EPiX',
  '331': 'FlixFling',
  '257': 'Fubo',
  '123': 'FXNow',
  '27@31': 'HBO',
  '384': 'HBO Max',
  '212': 'Hoopla',
  '15': 'Hulu',
  '238': 'IMDbTV',
  '191': 'Kanopy',
  '8': 'Netflix',
  '531': 'Paramount+',
  '386': 'Peacock',
  '387': 'Peacock Premium',
  '207': 'Roku',
  '37': 'Showtime',
  '99': 'Shudder',
  '43': 'Starz',
  '215': 'SyFy',
  '363': 'TNT',
  '73': 'Tubi',
  '322': 'USA',
  '7@332': 'Vudu',
  '10': 'Amazon (Buy/Rent)',
  '352': 'AMC',
  '2': 'Apple',
  '358': 'DirecTV',
  '105': 'Fandango',
  '3': 'Google',
  '192': 'YouTube',
}

const topOptions: DropdownOption[] = [
  { value: '9', label: 'Amazon (Stream)' },
  { value: '337', label: 'Disney+' },
  { value: '27@31', label: 'HBO' },
  { value: '384', label: 'HBO Max' },
  { value: '15', label: 'Hulu' },
  { value: '8', label: 'Netflix' },
  { value: '531', label: 'Paramount+' },
  { value: '386', label: 'Peacock' },
  { value: '387', label: 'Peacock Premium' },
  { value: '37', label: 'Showtime' },
  { value: '43', label: 'Starz' },
]

const streamingOptions: DropdownOption[] = [
  { value: '350', label: 'Apple TV' },
  { value: '289', label: 'Cinemax' },
  { value: '258', label: 'Critereon' },
  { value: '34', label: 'EPiX' },
  { value: '331', label: 'FlixFling' },
  { value: '257', label: 'Fubo' },
  { value: '123', label: 'FXNow' },
  { value: '212', label: 'Hoopla' },
  { value: '238', label: 'IMDbTV' },
  { value: '191', label: 'Kanopy' },
  { value: '207', label: 'Roku' },
  { value: '99', label: 'Shudder' },
  { value: '215', label: 'SyFy' },
  { value: '363', label: 'TNT' },
  { value: '73', label: 'Tubi' },
  { value: '322', label: 'USA' },
  { value: '7@332', label: 'Vudu' },
]

const buyrentOptions: DropdownOption[] = [
  { value: '10', label: 'Amazon (Buy/Rent)' },
  { value: '352', label: 'AMC' },
  { value: '2', label: 'Apple' },
  { value: '358', label: 'DirecTV' },
  { value: '105', label: 'Fandango' },
  { value: '3', label: 'Google' },
  { value: '192', label: 'YouTube' },
]

export const providerOptions: object[] = [
  {
    label: '',
    options: topOptions.map(({ value, label }) => {
      return {
        value: value,
        label: (
          <span className="filter-flex">
            {label}{' '}
            <img
              className="filter-icon"
              src={require(`../media/providers/${value.split('@')[0]}.png`)}
              alt={value}
            />
          </span>
        ),
      }
    }),
  },
  {
    label: 'Streaming',
    options: streamingOptions.map(({ value, label }) => {
      return {
        value: value,
        label: (
          <span className="filter-flex">
            {label}{' '}
            <img
              className="filter-icon"
              src={require(`../media/providers/${value.split('@')[0]}.png`)}
              alt={value}
            />
          </span>
        ),
      }
    }),
  },
  {
    label: 'Buy/Rent',
    options: buyrentOptions.map(({ value, label }) => {
      return {
        value: value,
        label: (
          <span className="filter-flex">
            {label}{' '}
            <img
              className="filter-icon"
              src={require(`../media/providers/${value.split('@')[0]}.png`)}
              alt={value}
            />
          </span>
        ),
      }
    }),
  },
]

const oscarOptions: DropdownOption[] = [
  {
    value: 'Best Animated Picture (Nominated)@Best Animated Picture (Winner)',
    label: 'Best Animated Picture (Nominated)',
  },
  {
    value: 'Best Animated Picture (Winner)',
    label: 'Best Animated Picture (Winner)',
  },
  {
    value: 'Best Picture (Nominated)@Best Picture (Winner)',
    label: 'Best Picture (Nominated)',
  },
  { value: 'Best Picture (Winner)', label: 'Best Picture (Winner)' },
]

const globesOptions: DropdownOption[] = [
  {
    value: 'Best Picture: Drama (Nominated)@Best Picture: Drama (Winner)',
    label: 'Best Picture: Drama (Nominated)',
  },
  {
    value: 'Best Picture: Drama (Winner)',
    label: 'Best Picture: Drama (Winner)',
  },
  {
    value:
      'Best Picture: Musical or Comedy (Nominated)@Best Picture: Musical or Comedy (Winner)',
    label: 'Best Picture: Musical or Comedy (Nominated)',
  },
  {
    value: 'Best Picture: Musical or Comedy (Winner)',
    label: 'Best Picture: Musical or Comedy (Winner)',
  },
]

export const awardOptions: object[] = [
  {
    label: 'Oscars',
    options: oscarOptions,
  },
  {
    label: 'Golden Globes',
    options: globesOptions,
  },
]

export const ratingOptions: DropdownOption[] = [
  {
    value: 'avg',
    label: (
      <span className="filter-flex">
        Average{' '}
        <img
          className="filter-icon"
          src={require(`../media/average.png`)}
          alt={'test'}
        />
      </span>
    ),
  },
  {
    value: 'jeff',
    label: (
      <span className="filter-flex">
        Jeff D. Lowe{' '}
        <img
          className="filter-icon"
          src={require(`../media/jdl.png`)}
          alt={'test'}
        />
      </span>
    ),
  },
  {
    value: 'kenjac',
    label: (
      <span className="filter-flex">
        KenJac{' '}
        <img
          className="filter-icon"
          src={require(`../media/kenjac.png`)}
          alt={'test'}
        />
      </span>
    ),
  },
]

export const sortOptions: DropdownOption[] = [
  { value: 'rating@ASC', label: 'High to Low (Rating)' },
  { value: 'rating@DESC', label: 'Low to High (Rating)' },
  { value: 'year@ASC', label: 'Oldest to Newest' },
  { value: 'year@DESC', label: 'Newest to Oldest' },
]
