export const genreOptions: object[] = [
    {value: "Action", label: "Action"},
    {value: "Adventure", label: "Adventure"},
    {value: "Animation", label: "Animation"},
    {value: "Comedy", label: "Comedy"},
    {value: "Comic", label: "Comic"},
    {value: "Crime", label: "Crime"},
    {value: "Disaster", label: "Disaster"},
    {value: "Drama", label: "Drama"},
    {value: "Dramedy", label: "Dramedy"},
    {value: "Family", label: "Family"},
    {value: "Fantasy", label: "Fantasy"},
    {value: "Horror", label: "Horror"},
    {value: "Music", label: "Music"},
    {value: "Musical", label: "Musical"},
    {value: "Mystery", label: "Mystery"},
    {value: "Romance", label: "Romance"},
    {value: "Sci-Fi", label: "Sci-Fi"},
]

export const subGenreOptions: object[] = [
    {value: 'Action Comedy', label: 'Action Comedy'},
    {value: 'Action Thriller', label: 'Action Thriller'},
    {value: 'Adult Animation', label: 'Adult Animation'},
    {value: 'Alien Invasion', label: 'Alien Invasion'},
    {value: 'Assassins, Hitmen, & Gunslingers', label: 'Assassins, Hitmen, & Gunslingers'},
    {value: 'BioPic', label: 'BioPic'},
    {value: 'BioPic & True Story', label: 'BioPic & True Story'},
    {value: 'Buddies & Screwballs', label: 'Buddies & Screwballs'},
    {value: 'Coming-of-Age', label: 'Coming-of-Age'},
    {value: 'Cooking', label: 'Cooking'},
    {value: 'Courtroom', label: 'Courtroom'},
    {value: 'Crime Thriller', label: 'Crime Thriller'},
    {value: 'Dance & Music', label: 'Dance & Music'},
    {value: 'Dark Humor', label: 'Dark Humor'},
    {value: 'Demons & Possession', label: 'Demons & Possession'},
    {value: 'Disaster & Apocalypse', label: 'Disaster & Apocalypse'},
    {value: 'Dystopian', label: 'Dystopian'},
    {value: 'Family Comedy', label: 'Family Comedy'},
    {value: 'Family Dynamics', label: 'Family Dynamics'},
    {value: 'Fast Cars & Getaways', label: 'Fast Cars & Getaways'},
    {value: 'Gangster, Mob, & Mafia', label: 'Gangster, Mob, & Mafia'},
    {value: 'Haunted & Paranormal', label: 'Haunted & Paranormal'},
    {value: 'Heist', label: 'Heist'},
    {value: 'Kids & Family', label: 'Kids & Family'},
    {value: 'LBGTQ+', label: 'LBGTQ+'},
    {value: 'Mall Cop', label: 'Mall Cop'},
    {value: 'Mecha & Gundam', label: 'Mecha & Gundam'},
    {value: 'Melodrama', label: 'Melodrama'},
    {value: 'Monsters & Creatures', label: 'Monsters & Creatures'},
    {value: 'Mystery & Suspense', label: 'Mystery & Suspense'},
    {value: 'Neo-Western', label: 'Neo-Western'},
    {value: 'Parody, Satire, & Spoof', label: 'Parody, Satire, & Spoof'},
    {value: 'Police & Detectives', label: 'Police & Detectives'},
    {value: 'Political', label: 'Political'},
    {value: 'Post-Apocalypse', label: 'Post-Apocalypse'},
    {value: 'Psychological Horror', label: 'Psychological Horror'},
    {value: 'Psychological Thriller', label: 'Psychological Thriller'},
    {value: 'Raunchy Humor', label: 'Raunchy Humor'},
    {value: 'Religious', label: 'Religious'},
    {value: 'Romantic Comedy', label: 'Romantic Comedy'},
    {value: 'Romantic Drama', label: 'Romantic Drama'},
    {value: 'Sci-Fi Thriller', label: 'Sci-Fi Thriller'},
    {value: 'Secret Agents & Espionage', label: 'Secret Agents & Espionage'},
    {value: 'Slasher, Shock, & Gore', label: 'Slasher, Shock, & Gore'},
    {value: 'Social & Political Commentary', label: 'Social & Political Commentary'},
    {value: 'Space Drama', label: 'Space Drama'},
    {value: 'Space Opera', label: 'Speace Opera'},
    {value: 'Sports', label: 'Sports'},
    {value: 'Stand-Up', label: 'Stand-Up'},
    {value: 'Stoner Flick', label: 'Stoner Flick'},
    {value: 'Sword & Sandal', label: 'Sword & Sandal'},
    {value: 'Teen Comedy', label: 'Teen Comedy'},
    {value: 'Teen Scream', label: 'Teen Scream'},
    {value: 'Video Game', label: 'Video Game'},
    {value: 'War', label: 'War'},
    {value: 'Western', label: 'Western'},
    {value: 'Witches & Wizards', label: 'Witches & Wizards'},
    {value: 'Young Adult', label: 'Young Adult'},
]

export const universeOptions: object[] = [
    {value: '20th Century Animation', label: '20th Century Animation'},
    {value: 'A Nightmare on Elm Street', label: 'A Nightmare on Elm Street'},
    {value: 'Aardman', label: 'Aardman'},
    {value: 'Ace Ventura', label: 'Ace Ventura'},
    {value: 'Adult Swim', label: 'Adult Swim'},
    {value: 'Alien', label: 'Alien'},
    {value: 'Alien vs. Predator', label: 'Alien vs. Predator'},
    {value: 'American Pie', label: 'American Pie'},
    {value: 'Austin Powers', label: 'Austin Powers'},
    {value: 'Avalanche Animation', label: 'Avalanche Animation'},
    {value: 'Baby Geniuses', label: 'Baby Geniuses'},
    {value: 'Back to the Future', label: 'Back to the Future'},
    {value: 'Bad Boys', label: 'Bad Boys'},
    {value: 'Before Franchise', label: 'Before Franchise'},
    {value: 'Beverly Hills Cop', label: 'Beverly Hills Cop'},
    {value: 'Blue Sky Animation', label: 'Blue Sky Animation'},
    {value: 'Bourne', label: 'Bourne'},
    {value: 'Cartoon Saloon', label: 'Cartoon Saloon'},
    {value: "Charlie's Angels", label: "Charlie's Angels"},
    {value: 'Crest Animation', label: 'Crest Animation'},
    {value: 'Dark Horse', label: 'Dark Horse'},
    {value: 'Dark Universe', label: 'Dark Universe'},
    {value: 'DC', label: 'DC'},
    {value: 'Die Hard', label: 'Die Hard'},
    {value: 'Dirty Harry', label: 'Dirty Harry'},
    {value: 'Disney', label: 'Disney'},
    {value: 'Dollars Trilogy', label: 'Dollars Trilogy'},
    {value: 'DreamWorks Animation', label: 'DreamWorks Animation'},
    {value: 'Fast & Furious', label: 'Fast & Furious'},
    {value: 'Final Destination', label: 'Final Destination'},
    {value: 'First Blood', label: 'First Blood'},
    {value: 'Friday the 13th', label: 'Friday the 13th'},
    {value: 'Ghostbusters', label: 'Ghostbusters'},
    {value: 'Godfather', label: 'Godfather'},
    {value: 'Halloween', label: 'Halloween'},
    {value: 'Hannibal Lecter', label: 'Hannibal Lecter'},
    {value: 'Happy Madison', label: 'Happy Madison'},
    {value: 'Harold & Kumar', label: 'Harold & Kumar'},
    {value: 'Home Alone', label: 'Home Alone'},
    {value: 'Huhu Animation', label: 'Huhu Animation'},
    {value: 'Illumination', label: 'Illumination'},
    {value: 'Indiana Jones', label: 'Indiana Jones'},
    {value: 'Jack Ryan', label: 'Jack Ryan'},
    {value: 'James Bond', label: 'James Bond'},
    {value: 'John Wick', label: 'John Wick'},
    {value: 'Jumanji', label: 'Jumanji'},
    {value: 'Jurassic Park', label: 'Jurassic Park'},
    {value: 'Kick-Ass', label: 'Kick-Ass'},
    {value: 'Laika Animation', label: 'Laika Animation'},
    {value: 'Lethal Weapon', label: 'Lethal Weapon'},
    {value: 'Lionsgate Animation', label: 'Lionsgate Animation'},
    {value: 'Lucasfilm Animation', label: 'Lucasfilm Animation'},
    {value: 'Mad Max', label: 'Mad Max'},
    {value: 'Major League', label: 'Major League'},
    {value: 'Marvel', label: 'Marvel'},
    {value: 'Matrix', label: 'Matrix'},
    {value: 'Men in Black', label: 'Men in Black'},
    {value: 'Middle-earth', label: 'Middle-earth'},
    {value: 'Mission: Impossible', label: 'Mission: Impossible'},
    {value: 'Monster Universe', label: 'Monster Universe'},
    {value: 'Monty Python', label: 'Monty Python'},
    {value: 'National Lampoon', label: 'National Lampoon'},
    {value: 'Nicholas Sparks', label: 'Nicholas Sparks'},
    {value: 'Nickelodeon', label: 'Nickelodeon'},
    {value: 'Ninja Turtles', label: 'Ninja Turtles'},
    {value: "Ocean's Franchise", label: "Ocean's Franchise"},
    {value: 'Open Road Animation', label: 'Open Road Animation'},
    {value: 'Paramount Animation', label: 'Paramount Animation'},
    {value: 'Paranormal Activity', label: 'Paranormal Activity'},
    {value: 'Pathé Animation', label: 'Pathé Animation'},
    {value: 'Planet of the Apes', label: 'Planet of the Apes'},
    {value: 'PlayStation', label: 'PlayStation'},
    {value: 'Predator', label: 'Predator'},
    {value: 'Public Domain', label: 'Public Domain'},
    {value: 'Rainmaker Animation', label: 'Rainmaker Animation'},
    {value: 'Reel FX Animation', label: 'Reel FX Animation'},
    {value: 'Resident Evil', label: 'Resident Evil'},
    {value: 'Rocky', label: 'Rocky'},
    {value: 'Rush Hour', label: 'Rush Hour'},
    {value: 'Saw', label: 'Saw'},
    {value: 'Scream', label: 'Scream'},
    {value: 'Sin City', label: 'Sin City'},
    {value: 'Sony Animation', label: 'Sony Animation'},
    {value: 'Star Wars', label: 'Star Wars'},
    {value: 'Star Trek', label: 'Star Trek'},
    {value: 'Starz Animation', label: 'Starz Animation'},
    {value: 'Studio Ghibli', label: 'Studio Ghibli'},
    {value: 'Summit Animation', label: 'Summit Animation'},
    {value: 'STX Animation', label: 'STX Animation'},
    {value: 'Terminator', label: 'Terminator'},
    {value: 'Texas Chain Saw', label: 'Texas Chain Saw'},
    {value: 'Three Flavours Cornetto', label: 'Three Flavours Cornetto'},
    {value: 'Transformers', label: 'Transformers'},
    {value: 'Transporter', label: 'Transporter'},
    {value: 'TriStar Animation', label: 'TriStar Animation'},
    {value: 'Twilight', label: 'Twilight'},
    {value: 'Tyler Perry', label: 'Tyler Perry'},
    {value: 'United Artists Animation', label: 'United Artists Animation'},
    {value: 'Universal Animation', label: 'Universal Animation'},
    {value: 'View Askewniverse', label: 'View Askewniverse'},
    {value: 'Wizarding World', label: 'Wizarding World'},
    {value: 'Warner Bros. Animation', label: 'Warner Bros. Animation'},
    { value: 'xXx', label: 'xXx' },
    {value: 'Zorro', label: 'Zorro'},
]

export const subUniverseOptions: object[] = [
    {value: 'Bay Transformers', label: 'Bay Transformers'},
    {value: 'Bond - Brosnan', label: 'Bond - Brosnan'},
    {value: 'Bond - Connery', label: 'Bond - Connery'},
    {value: 'Bond - Craig', label: 'Bond - Craig'},
    {value: 'Bond - Dalton', label: 'Bond - Dalton'},
    {value: 'Bond - Lazenby', label: 'Bond - Lazenby'},
    {value: 'Bond - Moore', label: 'Bond - Moore'},
    {value: 'DCEU', label: 'DCEU'},
    {value: 'Disney Animation', label: 'Disney Animation'},
    {value: 'Dr. Seuss', label: 'Dr. Seuss'},
    {value: 'Fantastic Beasts', label: 'Fantastic Beasts'},
    {value: 'Gnomes', label: 'Gnomes'},
    {value: 'Hanna-Barbera', label: 'Hanna-Barbera'},
    {value: 'Harry Potter', label: 'Harry Potter'},
    {value: 'Hellboy', label: 'Hellboy'},
    {value: 'Honey, I Shrunk', label: 'Honey, I Shrunk'},
    {value: 'Hotel Transylvania', label: 'Hotel Transylvania'},
    {value: 'How To Train Your Dragon', label: 'How To Train Your Dragon'},
    {value: 'Ice Age', label: 'Ice Age'},
    {value: 'Jurassic Original', label: 'Jurassic Original'},
    {value: 'Jurassic Sequel', label: 'Jurassic Sequel'},
    {value: 'Kung Fu Panda', label: 'Kung Fu Panda'},
    {value: 'LEGO', label: 'LEGO'},
    {value: 'Live-Action', label: 'Live-Action'},
    {value: 'Live-Action Remake', label: 'Live-Action Remake'},
    {value: 'Madagascar', label: 'Madagascar'},
    {value: 'Mary Poppins', label: 'Mary Poppins'},
    {value: 'MCU', label: 'MCU'},
    {value: 'Mighty Ducks', label: 'Mighty Ducks'},
    {value: 'Minions', label: 'Minions'},
    {value: 'Mummy', label: 'Mummy'},
    {value: 'Muppets', label: 'Muppets'},
    {value: 'Narnia', label: 'Narnia'},
    {value: 'Non-DCEU', label: 'Non-DCEU'},
    {value: 'Non-MCU', label: 'Non-MCU'},
    {value: 'Pirates', label: 'Pirates'},
    {value: 'Pixar', label: 'Pixar'},
    {value: 'Planet of the Apes New', label: 'Planet of the Apes New'},
    {value: 'Planet of the Apes Old', label: 'Planet of the Apes Old'},
    {value: 'Planet of the Apes Reboot', label: 'Planet of the Apes Reboot'},
    {value: 'Shrek', label: 'Shrek'},
    {value: 'Smurfs', label: 'Smurfs'},
    {value: 'Sony Pictures Marvel Universe', label: 'Sony Pictures Marvel Universe'},
    {value: 'Star Trek Kelvin', label: 'Star Trek Kelvin'},
    {value: 'Stark Trek Next Generation', label: 'Stark Trek Next Generation'},
    {value: 'Star Trek Original Series', label: 'Star Trek Original Series'},
    {value: 'Star Wars Original', label: 'Star Wars Original'},
    {value: 'Star Wars Prequel', label: 'Star Wars Prequel'},
    {value: 'Star Wars Sequel', label: 'Star Wars Sequel'},
    {value: 'Star Wars Standalone', label: 'Star Wars Standalone'},
    {value: 'Transformers Standalone', label: 'Transformers Standalone'},
    {value: 'Tron', label: 'Tron'},
    {value: 'Vacation', label: 'Vacation'},
    {value: 'X-Men', label: 'X-Men'},
]

export const characterOptions: object[] = [
    { value: 'Ant-Man', label: 'Ant-Man' },
    { value: 'Aquaman', label: 'Aquaman' },
    { value: 'Avengers', label: 'Avengers' },
    { value: 'Batman', label: 'Batman' },
    { value: 'Black Panther', label: 'Black Panther' },
    { value: 'Blade', label: 'Blade' },
    { value: 'Captain America', label: 'Captain America' },
    { value: 'Captain Marvel', label: 'Captain Marvel' },
    { value: 'Cat in the Hat', label: 'Cat in the Hat' },
    { value: 'Catwoman', label: 'Catwoman' },
    { value: 'Constantine', label: 'Constantine' },
    { value: 'Creed', label: 'Creed' },
    { value: 'Daredevil', label: 'Daredevil' },
    { value: 'Deadpool', label: 'Deadpool' },
    { value: 'Doctor Strange', label: 'Doctor Strange' },
    { value: 'Dracula', label: 'Dracula' },
    { value: 'Elektra', label: 'Elektra' },
    { value: 'Fantastic Four', label: 'Fantastic Four' },
    { value: 'Freddy Krueger', label: 'Freddy Krueger' },
    { value: 'Ghost Rider', label: 'Ghost Rider' },
    { value: 'Godzilla', label: 'Godzilla' },
    { value: 'Green Lantern', label: 'Green Lantern' },
    { value: 'Grinch', label: 'Grinch' },
    { value: 'Guardians of the Galaxy', label: 'Guardians of the Galaxy' },
    { value: 'Harley Quinn', label: 'Harley Quinn' },
    { value: 'Hellboy', label: 'Hellboy' },
    { value: 'Howard the Duck', label: 'Howard the Duck' },
    { value: 'Hulk', label: 'Hulk' },
    { value: 'Indiana Jones', label: 'Indiana Jones' },
    { value: 'Iron Man', label: 'Iron Man' },
    { value: 'Jason Vorhees', label: 'Jason Vorhees' },
    { value: 'Joker', label: 'Joker' },
    { value: 'Jonah Hex', label: 'Jonah Hex' },
    { value: 'Justice League', label: 'Justice League' },
    { value: 'King Kong', label: 'King Kong' },
    { value: 'Leatherface', label: 'Leatherface' },
    { value: 'Man with No Name', label: 'Man with No Name' },
    { value: 'Michael Myers', label: 'Michael Myers' },
    { value: 'Mummy', label: 'Mummy' },
    { value: 'Predator', label: 'Predator' },
    { value: 'Punisher', label: 'Punisher' },
    { value: 'Rambo', label: 'Rambo' },
    { value: 'Rocky Balboa', label: 'Rocky Balboa' },
    { value: 'Scooby-Doo', label: 'Scooby-Doo' },
    { value: 'Shazam!', label: 'Shazam!' },
    { value: 'Shrek', label: 'Shrek' },
    { value: 'Simpsons', label: 'Simpsons' },
    { value: 'Spider-Man', label: 'Spider-Man' },
    { value: 'Suicide Squad', label: 'Suicide Squad' },
    { value: 'Supergirl', label: 'Supergirl' },
    { value: 'Superman', label: 'Superman' },
    { value: 'Swamp Thing', label: 'Swamp Thing' },
    { value: 'Thor', label: 'Thor' },
    { value: 'Van Helsing', label: 'Van Helsing' },
    { value: 'Venom', label: 'Venom' },
    { value: 'Wolfman', label: 'Wolfman' },
    { value: 'Wolverine', label: 'Wolverine' },
    { value: 'Wonder Woman', label: 'Wonder Woman' },
    { value: 'X-Men', label: 'X-Men' },
    { value: 'Xander Cage', label: 'Xander Cage' },
]

export const sportholidayOptions: object[] = [
    { value: 'Baseball', label: 'Baseball' },
    { value: 'Basketball', label: 'Basketball' },
    { value: 'Billiards', label: 'Billiards' },
    { value: 'Bowling', label: 'Bowling' },
    { value: 'Boxing', label: 'Boxing' },
    { value: 'Cheerleading', label: 'Cheerleading' },
    { value: 'Chess', label: 'Chess' },
    { value: 'Christmas', label: 'Christmas' },
    { value: 'Dodgeball', label: 'Dodgeball' },
    { value: 'Dracula', label: 'Dracula' },
    { value: 'Football', label: 'Football' },
    { value: 'Golf', label: 'Golf' },
    { value: 'Hockey', label: 'Hockey' },
    { value: 'Horse Racing', label: 'Horse Racing' },
    { value: 'Martial Arts', label: 'Martial Arts' },
    { value: 'Olympics', label: 'Olympics' },
    { value: 'Poker', label: 'Poker' },
    { value: 'Racing', label: 'Racing' },
    { value: 'Rugby', label: 'Rugby' },
    { value: 'Soccer', label: 'Soccer' },
    { value: 'Surfing', label: 'Surfing' },
    { value: 'Table Tennis', label: 'Table Tennis' },
    { value: 'Tennis', label: 'Tennis' },
    { value: 'Volleyball', label: 'Volleyball' },
    { value: 'Wrestling', label: 'Wrestling' },
]

export const sortOptions: object[] = [
    {value: "", label: "Best Match"},
    {value: "ASC", label: "Rating High to Low"},
    {value: "DESC", label: "Rating Low to High"},
]