export default interface Review {
    id?: number;
    avgrank?: number;
    movie: string;
    avgtotal: number;
    jlrank?: number;
    jeff?: number;
    kjrank?: number;
    kenjac?: number;
    buttered?: boolean;
    director?: string;
    genre?: string;
    subgenre?: string;
    studiocompany?: string;
    universe?: string;
    subuniverse?: string;
    character?: string;
    sport?: string;
    holiday?: string;
    year?: number;
    decade?: number
    poster?: string;
    plot?: string;
    actors?: string;
    video_key?: string;
    runtime?: number;
    oscar_winner?: boolean;
    oscars?: string;
    oscars_animated?: string;
    oscars_director?: string;
    best_actor?: string;
    best_actress?: string;
    support_actor?: string;
    support_actress?: string;
    goldenglobes?: string;
    rt?: string;
    imdb?: string;
    metacritic?: string;
}